/* AUTOLINE TRIGGERS */

CREATE OR REPLACE FUNCTION autoline_to_dim_ad() RETURNS TRIGGER AS
$BODY$
BEGIN
    INSERT INTO WH.DIM_AD (
        TITULO,
        TIPO_ANUNCIO,
        NOME_VENDEDOR,
        CIDADE_VENDEDOR,
        ESTADO_VENDEDOR,
        UF_VENDEDOR,
        BAIRRO,
        ENDERECO,
        COMPLEMENTO_ENDERECO,
        DOCUMENTO_VENDEDOR,
        EMAIL,
        CELULAR,
        TELEFONE,
        WHATSAPP,
        TIPO_VENDEDOR,
        VENDEDOR_PJ,
        ACEITA_TROCA,
        TROCA_COM_TROCO,
        ENTREGA_CARRO,
        COMENTARIO_DONO,
        PLACA,
        LINK_AD,
        DATA_CRIACAO_AD
    )
    VALUES(
        NEW.INFORMACOES_ADICIONAIS,
        NULL,
        NEW.NOME_VENDEDOR,
        NEW.CIDADE,
        NEW.ESTADO,
        NEW.UF,
        NEW.BAIRRO,
        NEW.ENDERECO,
        NEW.COMPLEMENTO_ENDERECO,
        NEW.DOCUMENTO_VENDEDOR,
        NEW.EMAIL,
        NEW.CELULAR,
        NEW.TELEFONE,
        NEW.WHATSAPP,
        NEW.TIPO_VENDEDOR,
        NEW.VENDEDOR_PJ,
        NEW.ACEITA_TROCA,
        NULL,
        NULL,
        NULL,
        NEW.PLACA,
        NEW.LINK_AD,
        NEW.DATA_CRIACAO_AD
    ) ON CONFLICT DO NOTHING;
    RETURN NEW;
END;
$BODY$
language plpgsql;

CREATE OR REPLACE FUNCTION autoline_to_dim_cars() RETURNS TRIGGER AS
$BODY$
BEGIN
    INSERT INTO WH.DIM_CARS (
        FABRICANTE,
        TIPO_VEICULO,
        MODELO,
        VERSAO,
        ANO_FABRICACAO,
        ANO_MODELO,
        TRANSMISSAO,
        QNTD_PORTAS,
        CORPO_VEICULO,
        COR,
        COR_SECUNDARIA,
        COMBUSTIVEL,
        MOTOR
    ) VALUES (
        NEW.FABRICANTE,
        NEW.TIPO_VEICULO,
        NEW.MODELO,
        NEW.VERSAO,
        NEW.ANO_FABRICACAO,
        NEW.ANO_MODELO,
        NEW.TRANSMISSAO,
        NEW.QNTD_PORTAS,
        NEW.CORPO_VEICULO,
        NEW.COR,
        NEW.COR_SECUNDARIA,
        NEW.COMBUSTIVEL,
        NEW.MOTOR
    ) ON CONFLICT DO NOTHING;
    RETURN NEW;
END;
$BODY$
language plpgsql;

CREATE OR REPLACE FUNCTION autoline_to_dim_resources() RETURNS TRIGGER AS
$BODY$
BEGIN
    INSERT INTO WH.DIM_RESOURCES (
        FINANCIAVEL,
        FINANCIADO,
        IMPOSTOS_PAGOS,
        REGISTRAMENTO_PAGO,
        QUITADO,
        ALIENADO,
        REVISOES_PELA_AGENDA_CARRO,
        REVISOES_PELA_CONCESSIONARIA,
        UNICO_DONO,
        COLECIONADOR,
        ADAPTADO_DEFICIENCIA,
        BLINDADO,
        LICENCIADO,
        IPVA_PAGO,
        GARANTIA_DE_FABRICA,
        AIRBAG,
        AIRBAG_DUPLO,
        ALARME,
        AR_CONDICIONADO,
        AR_QUENTE,
        BANCO_REGULA_ALTURA,
        BANCO_COM_AQUECIMENTO,
        BANCO_DE_COURO,
        CAPOTA_MARITIMA,
        MP3_CD_PLAYER,
        CD_PLAYER,
        DISQUETEIRA,
        DVD_PLAYER,
        COMPUTAR_DE_BORDO,
        CONTROLE_AUTOMATICO_VEL,
        CONTROLE_TRACAO,
        DESEMBACADOR_TRASEIRO,
        DIR_HIDRAULICA,
        DIR_ELETRICA,
        ENCOSTO_CABECA_TRASEIRO,
        FAROL_DE_XENONIO,
        FAROL_DE_MILHA,
        FAROL_NEBLINA,
        FREIO_ABS,
        GPS,
        LIMPADOR_TRASEIRO,
        PROTETOR_CACAMBA,
        RADIO,
        RADIO_TOCAFITA,
        KIT_MULTIMIDIA,
        RETROVISOR_FOTOCROMICO,
        RETROVISOR_ELETRICO,
        RODAS_LIGA_LEVE,
        SENSOR_DE_CHUVA,
        SENSOR_DE_ESTACIONAMENTO,
        TETO_SOLAR,
        TRACAO_QUATRO_POR_QUATRO,
        TRAVAS_ELETRICAS,
        VIDROS_ELETRICOS,
        VOLANTE_REG_ALTURA,
        PILOTO_AUTOMATICO,
        ESCAPAMENTO_ESPORTIVO
    ) VALUES (
        NEW.FINANCIAVEL,
        NEW.FINANCIADO,
        NEW.IMPOSTOS_PAGOS,
        NEW.REGISTRAMENTO_PAGO,
        NEW.QUITADO,
        NULL,
        NULL,
        NULL,
        NEW.DONO_UNICO,
        NEW.COLECIONADOR,
        NEW.ADAPTADO_DEFICIENCIA,
        NEW.BLINDADO,
        NULL,
        NULL,
        NEW.GARANTIA_DE_FABRICA,
        NEW.AIRBAG,
        NEW.AIRBAG_DUPLO,
        NEW.ALARME,
        NEW.AR_CONDICIONADO,
        NEW.AR_QUENTE,
        NEW.BANCO_REGULA_ALTURA,
        NEW.BANCO_COM_AQUECIMENTO,
        NEW.BANCO_DE_COURO,
        NEW.CAPOTA_MARITIMA,
        NEW.MP3_CD_PLAYER,
        NEW.CD_PLAYER,
        NEW.DISQUETEIRA,
        NEW.DVD_PLAYER,
        NEW.COMPUTAR_DE_BORDO,
        NEW.CONTROLE_AUTOMATICO_VEL,
        NEW.CONTROLE_TRACAO,
        NEW.DESEMBACADOR_TRASEIRO,
        NEW.DIR_HIDRAULICA,
        NEW.DIR_ELETRICA,
        NEW.ENCOSTO_CABECA_TRASEIRO,
        NEW.FAROL_DE_XENONIO,
        NEW.FAROL_DE_MILHA,
        NEW.FAROL_NEBLINA,
        NEW.FREIO_ABS,
        NEW.GPS,
        NEW.LIMPADOR_TRASEIRO,
        NEW.PROTETOR_CACAMBA,
        NEW.RADIO,
        NEW.RADIO_TOCAFITA,
        NEW.KIT_MULTIMIDIA,
        NEW.RETROVISOR_FOTOCROMICO,
        NEW.RETROVISOR_ELETRICO,
        NEW.RODAS_LIGA_LEVE,
        NEW.SENSOR_DE_CHUVA,
        NEW.SENSOR_DE_ESTACIONAMENTO,
        NEW.TETO_SOLAR,
        NEW.TRACAO_QUATRO_POR_QUATRO,
        NEW.TRAVAS_ELETRICAS,
        NEW.VIDROS_ELETRICOS,
        NEW.VOLANTE_REG_ALTURA,
        NEW.PILOTO_AUTOMATICO,
        NEW.ESCAPAMENTO_ESPORTIVO
    ) ON CONFLICT DO NOTHING;
    RETURN NEW;
END;
$BODY$
language plpgsql;

CREATE OR REPLACE FUNCTION autoline_to_fact() RETURNS TRIGGER AS 
$BODY$
BEGIN
    INSERT INTO WH.FACT_AD
    SELECT
        DEFAULT,
        AD.AD_KEY,
        CAR.CAR_KEY,
        RES.RESOURCE_KEY,
        N.KILOMETRAGEM,
        N.PRECO,
        NULL,
        N.PRECO_FIPE
    FROM ( SELECT NEW.*) AS N
    LEFT JOIN WH.DIM_AD as AD
    ON AD.TITULO = N.INFORMACOES_ADICIONAIS AND
        AD.TIPO_ANUNCIO = NULL AND
        AD.NOME_VENDEDOR = N.NOME_VENDEDOR AND
        AD.CIDADE_VENDEDOR = N.CIDADE AND
        AD.ESTADO_VENDEDOR = N.ESTADO AND
        AD.NOME_VENDEDOR = N.NOME_VENDEDOR AND
        AD.CIDADE_VENDEDOR = N.CIDADE AND
        AD.ESTADO_VENDEDOR = N.ESTADO AND
        AD.UF_VENDEDOR = N.UF AND
        AD.BAIRRO = N.BAIRRO AND
        AD.ENDERECO = N.ENDERECO AND
        AD.COMPLEMENTO_ENDERECO = N.COMPLEMENTO_ENDERECO AND
        AD.DOCUMENTO_VENDEDOR = N.DOCUMENTO_VENDEDOR AND
        AD.EMAIL = N.EMAIL AND
        AD.CELULAR = N.CELULAR AND
        AD.TELEFONE = N.TELEFONE AND
        AD.WHATSAPP = N.WHATSAPP AND
        AD.TIPO_VENDEDOR = N.TIPO_VENDEDOR AND
        AD.VENDEDOR_PJ = N.VENDEDOR_PJ AND
        AD.ACEITA_TROCA = N.ACEITA_TROCA AND
        AD.TROCA_COM_TROCO = NULL AND
        AD.ENTREGA_CARRO = NULL AND
        AD.COMENTARIO_DONO = NULL AND
        AD.PLACA = N.PLACA AND
        AD.LINK_AD = N.LINK_AD AND
        AD.DATA_CRIACAO_AD = N.DATA_CRIACAO_AD
        AD.UF_VENDEDOR = N.UF AND
        AD.BAIRRO = N.BAIRRO AND
        AD.ENDERECO = N.ENDERECO AND
        AD.COMPLEMENTO_ENDERECO = N.COMPLEMENTO_ENDERECO AND
        AD.DOCUMENTO_VENDEDOR = N.DOCUMENTO_VENDEDOR AND
        AD.EMAIL = N.EMAIL AND
        AD.CELULAR = N.CELULAR AND
        AD.TELEFONE = N.TELEFONE AND
        AD.WHATSAPP = N.WHATSAPP AND
        AD.TIPO_VENDEDOR = N.TIPO_VENDEDOR AND
        AD.VENDEDOR_PJ = N.VENDEDOR_PJ AND
        AD.ACEITA_TROCA = N.ACEITA_TROCA AND
        AD.TROCA_COM_TROCO = NULL AND
        AD.ENTREGA_CARRO = NULL AND
        AD.COMENTARIO_DONO = NULL AND
        AD.PLACA = N.PLACA AND
        AD.LINK_AD = N.LINK_AD AND
        AD.DATA_CRIACAO_AD = N.DATA_CRIACAO_AD
    LEFT JOIN WH.DIM_CARS AS CARS
    ON CARS.FABRICANTE = N.FABRICANTE AND
        CARS.TIPO_VEICULO = N.TIPO_VEICULO AND
        CARS.MODELO = N.MODELO AND
        CARS.VERSAO = N.VERSAO AND
        CARS.ANO_FABRICACAO = N.ANO_FABRICACAO AND
        CARS.ANO_MODELO = N.ANO_MODELO AND
        CARS.TRANSMISSAO = N.TRANSMISSAO AND
        CARS.QNTD_PORTAS = N.QNTD_PORTAS AND
        CARS.CORPO_VEICULO = N.CORPO_VEICULO AND
        CARS.COR = N.COR AND
        CARS.COR_SECUNDARIA = N.COR_SECUNDARIA AND
        CARS.COMBUSTIVEL = N.COMBUSTIVEL AND
        CARS.MOTOR = N.MOTOR
    LEFT JOIN WH.DIM_RESOURCES AS RES
    ON RES.FINANCIAVEL = N.FINANCIAVEL AND
        RES.FINANCIADO = N.FINANCIADO AND
        RES.IMPOSTOS_PAGOS = N.IMPOSTOS_PAGOS AND
        RES.REGISTRAMENTO_PAGO = N.REGISTRAMENTO_PAGO AND
        RES.QUITADO = N.QUITADO AND
        RES.ALIENADO = NULL AND
        RES.REVISOES_PELA_AGENDA_CARRO = NULL AND
        RES.REVISOES_PELA_CONCESSIONARIA = NULL AND
        RES.UNICO_DONO = N.DONO_UNICO AND
        RES.COLECIONADOR = N.COLECIONADOR AND
        RES.ADAPTADO_DEFICIENCIA = N.ADAPTADO_DEFICIENCIA AND
        RES.BLINDADO = N.BLINDADO AND
        RES.LICENCIADO = NULL AND
        RES.IPVA_PAGO = NULL AND
        RES.GARANTIA_DE_FABRICA = N.GARANTIA_DE_FABRICA AND
        RES.AIRBAG = N.AIRBAG AND
        RES.AIRBAG_DUPLO = N.AIRBAG_DUPLO AND
        RES.ALARME = N.ALARME AND
        RES.AR_CONDICIONADO = N.AR_CONDICIONADO AND
        RES.AR_QUENTE = N.AR_QUENTE AND
        RES.BANCO_REGULA_ALTURA = N.BANCO_REGULA_ALTURA AND
        RES.BANCO_COM_AQUECIMENTO = N.BANCO_COM_AQUECIMENTO AND
        RES.BANCO_DE_COURO = N.BANCO_DE_COURO AND
        RES.CAPOTA_MARITIMA = N.CAPOTA_MARITIMA AND
        RES.MP3_CD_PLAYER = N.MP3_CD_PLAYER AND
        RES.CD_PLAYER = N.CD_PLAYER AND
        RES.DISQUETEIRA = N.DISQUETEIRA AND
        RES.DVD_PLAYER = N.DVD_PLAYER AND
        RES.COMPUTAR_DE_BORDO = N.COMPUTAR_DE_BORDO AND
        RES.CONTROLE_AUTOMATICO_VEL = N.CONTROLE_AUTOMATICO_VEL AND
        RES.CONTROLE_TRACAO = N.CONTROLE_TRACAO AND
        RES.DESEMBACADOR_TRASEIRO = N.DESEMBACADOR_TRASEIRO AND
        RES.DIR_HIDRAULICA = N.DIR_HIDRAULICA AND
        RES.DIR_ELETRICA = N.DIR_ELETRICA AND
        RES.ENCOSTO_CABECA_TRASEIRO = N.ENCOSTO_CABECA_TRASEIRO AND
        RES.FAROL_DE_XENONIO = N.FAROL_DE_XENONIO AND
        RES.FAROL_DE_MILHA = N.FAROL_DE_MILHA AND
        RES.FAROL_NEBLINA = N.FAROL_NEBLINA AND
        RES.FREIO_ABS = N.FREIO_ABS AND
        RES.GPS = N.GPS AND
        RES.LIMPADOR_TRASEIRO = N.LIMPADOR_TRASEIRO AND
        RES.PROTETOR_CACAMBA = N.PROTETOR_CACAMBA AND
        RES.RADIO = N.RADIO AND
        RES.RADIO_TOCAFITA = N.RADIO_TOCAFITA AND
        RES.KIT_MULTIMIDIA = N.KIT_MULTIMIDIA AND
        RES.RETROVISOR_FOTOCROMICO = N.RETROVISOR_FOTOCROMICO AND
        RES.RETROVISOR_ELETRICO = N.RETROVISOR_ELETRICO AND
        RES.RODAS_LIGA_LEVE = N.RODAS_LIGA_LEVE AND
        RES.SENSOR_DE_CHUVA = N.SENSOR_DE_CHUVA AND
        RES.SENSOR_DE_ESTACIONAMENTO = N.SENSOR_DE_ESTACIONAMENTO AND
        RES.TETO_SOLAR = N.TETO_SOLAR AND
        RES.TRACAO_QUATRO_POR_QUATRO = N.TRACAO_QUATRO_POR_QUATRO AND
        RES.TRAVAS_ELETRICAS = N.TRAVAS_ELETRICAS AND
        RES.VIDROS_ELETRICOS = N.VIDROS_ELETRICOS AND
        RES.VOLANTE_REG_ALTURA = N.VOLANTE_REG_ALTURA AND
        RES.PILOTO_AUTOMATICO = N.PILOTO_AUTOMATICO AND
        RES.ESCAPAMENTO_ESPORTIV = N.ESCAPAMENTO_ESPORTIVO
    RETURN NEW;
END;
$BODY$
language plpgsql;

CREATE TRIGGER d
    AFTER INSERT ON STG.AUTOLINE
    FOR EACH ROW
    EXECUTE FUNCTION autoline_to_fact();

CREATE TRIGGER c
    AFTER INSERT ON STG.AUTOLINE
    FOR EACH ROW
    EXECUTE FUNCTION autoline_to_dim_resources();

CREATE TRIGGER b
    AFTER INSERT ON STG.AUTOLINE
    FOR EACH ROW
    EXECUTE FUNCTION autoline_to_dim_cars();

CREATE TRIGGER a
    AFTER INSERT ON STG.AUTOLINE
    FOR EACH ROW
    EXECUTE FUNCTION autoline_to_dim_ad();

/* WEBMOTORS TRIGGERS */

CREATE OR REPLACE FUNCTION webmotors_to_dim_ad() RETURNS TRIGGER AS
$BODY$
BEGIN
    INSERT INTO WH.DIM_AD (
        TITULO,
        TIPO_ANUNCIO,
        NOME_VENDEDOR,
        CIDADE_VENDEDOR,
        ESTADO_VENDEDOR,
        UF_VENDEDOR,
        BAIRRO,
        ENDERECO,
        COMPLEMENTO_ENDERECO,
        DOCUMENTO_VENDEDOR,
        EMAIL,
        CELULAR,
        TELEFONE,
        WHATSAPP,
        TIPO_VENDEDOR,
        VENDEDOR_PJ,
        ACEITA_TROCA,
        TROCA_COM_TROCO,
        ENTREGA_CARRO,
        COMENTARIO_DONO,
        PLACA,
        LINK_AD,
        DATA_CRIACAO_AD
    ) VALUES (
        NEW.TITULO,
        NEW.TIPO_ANUNCIO,
        NULL,
        NEW.CIDADE_VENDEDOR,
        NEW.ESTADO_VENDEDOR,
        NEW.UF_VENDEDOR,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NEW.TIPO_VENDEDOR,
        NULL,
        NEW.ACEITA_TROCA,
        NEW.TROCA_COM_TROCO,
        NEW.ENTREGA_CARRO,
        NEW.COMENTARIO_DONO,
        NULL,
        NULL,
        NULL
    ) ON CONFLICT DO NOTHING;
    RETURN NEW;
END;
$BODY$
language plpgsql;

CREATE OR REPLACE FUNCTION webmotors_to_dim_cars() RETURNS TRIGGER AS
$BODY$
BEGIN
    INSERT INTO WH.DIM_CARS (
        FABRICANTE,
        TIPO_VEICULO,
        MODELO,
        VERSAO,
        ANO_FABRICACAO,
        ANO_MODELO,
        TRANSMISSAO,
        QNTD_PORTAS,
        CORPO_VEICULO,
        COR,
        COR_SECUNDARIA,
        COMBUSTIVEL,
        MOTOR
    ) VALUES (
        NEW.FABRICANTE,
        NULL,
        NEW.MODELO,
        NEW.VERSAO,
        NEW.ANO_FABRICACAO,
        NEW.ANO_MODELO,
        NEW.TRANSMISSAO,
        NEW.QNTD_PORTAS,
        NEW.CORPO_VEICULO,
        NEW.COR,
        NULL,
        NEW.COMBUSTIVEL,
        NULL
    ) ON CONFLICT DO NOTHING;
    RETURN NEW;
END;
$BODY$
language plpgsql;

CREATE OR REPLACE FUNCTION webmotors_to_dim_resources() RETURNS TRIGGER AS
$BODY$
BEGIN
    INSERT INTO WH.DIM_RESOURCES (
        FINANCIAVEL,
        FINANCIADO,
        IMPOSTOS_PAGOS,
        REGISTRAMENTO_PAGO,
        QUITADO,
        ALIENADO,
        REVISOES_PELA_AGENDA_CARRO,
        REVISOES_PELA_CONCESSIONARIA,
        UNICO_DONO,
        COLECIONADOR,
        ADAPTADO_DEFICIENCIA,
        BLINDADO,
        LICENCIADO,
        IPVA_PAGO,
        GARANTIA_DE_FABRICA,
        AIRBAG,
        AIRBAG_DUPLO,
        ALARME,
        AR_CONDICIONADO,
        AR_QUENTE,
        BANCO_REGULA_ALTURA,
        BANCO_COM_AQUECIMENTO,
        BANCO_DE_COURO,
        CAPOTA_MARITIMA,
        MP3_CD_PLAYER,
        CD_PLAYER,
        DISQUETEIRA,
        DVD_PLAYER,
        COMPUTAR_DE_BORDO,
        CONTROLE_AUTOMATICO_VEL,
        CONTROLE_TRACAO,
        DESEMBACADOR_TRASEIRO,
        DIR_HIDRAULICA,
        DIR_ELETRICA,
        ENCOSTO_CABECA_TRASEIRO,
        FAROL_DE_XENONIO,
        FAROL_DE_MILHA,
        FAROL_NEBLINA,
        FREIO_ABS,
        GPS,
        LIMPADOR_TRASEIRO,
        PROTETOR_CACAMBA,
        RADIO,
        RADIO_TOCAFITA,
        KIT_MULTIMIDIA,
        RETROVISOR_FOTOCROMICO,
        RETROVISOR_ELETRICO,
        RODAS_LIGA_LEVE,
        SENSOR_DE_CHUVA,
        SENSOR_DE_ESTACIONAMENTO,
        TETO_SOLAR,
        TRACAO_QUATRO_POR_QUATRO,
        TRAVAS_ELETRICAS,
        VIDROS_ELETRICOS,
        VOLANTE_REG_ALTURA,
        PILOTO_AUTOMATICO,
        ESCAPAMENTO_ESPORTIVO
    ) VALUES (
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NEW.ALIENADO,
        NEW.REVISOES_PELA_AGENDA_CARRO,
        NEW.REVISOES_PELA_CONCESSIONARIA,
        NEW.UNICO_DONO,
        NULL,
        NULL,
        NEW.BLINDADO,
        NEW.LICENCIADO,
        NEW.IPVA_PAGO,
        NEW.GARANTIA_DE_FABRICA,
        NEW.AIRBAG,
        NULL,
        NEW.ALARME,
        NEW.AR_CONDICIONADO,
        NEW.AR_QUENTE,
        NEW.BANCO_REGULA_ALTURA,
        NEW.BANCO_COM_AQUECIMENTO,
        NEW.BANCO_DE_COURO,
        NEW.CAPOTA_MARITIMA,
        NEW.MP3_CD_PLAYER,
        NEW.CD_PLAYER,
        NEW.DISQUETEIRA,
        NEW.DVD_PLAYER,
        NEW.COMPUTAR_DE_BORDO,
        NEW.CONTROLE_AUTOMATICO_VEL,
        NEW.CONTROLE_TRACAO,
        NEW.DESEMBACADOR_TRASEIRO,
        NEW.DIR_HIDRAULICA,
        NULL,
        NEW.ENCOSTO_CABECA_TRASEIRO,
        NEW.FAROL_DE_XENONIO,
        NULL,
        NULL,
        NEW.FREIO_ABS,
        NEW.GPS,
        NEW.LIMPADOR_TRASEIRO,
        NEW.PROTETOR_CACAMBA,
        NEW.RADIO,
        NEW.RADIO_TOCAFITA,
        NULL,
        NEW.RETROVISOR_FOTOCROMICO,
        NEW.RETROVISOR_ELETRICO,
        NEW.RODAS_LIGA_LEVE,
        NEW.SENSOR_DE_CHUVA,
        NEW.SENSOR_DE_ESTACIONAMENTO,
        NEW.TETO_SOLAR,
        NEW.TRACAO_QUATRO_POR_QUATRO,
        NEW.TRAVAS_ELETRICAS,
        NEW.VIDROS_ELETRICOS,
        NEW.VOLANTE_REG_ALTURA,
        NULL,
        NULL
    ) ON CONFLICT DO NOTHING;
    RETURN NEW;
END;
$BODY$
language plpgsql;

CREATE OR REPLACE FUNCTION webmotors_to_fact() RETURNS TRIGGER AS 
$BODY$
BEGIN
    INSERT INTO WH.FACT_AD
    SELECT
        DEFAULT,
        AD.AD_KEY,
        CAR.CAR_KEY,
        RES.RESOURCE_KEY,
        N.KILOMETRAGEM,
        N.PRECO,
        N.PRECO_DESEJADO,
        N.PORCENTAGEM_FIPE
    FROM (SELECT NEW.*) AS N
    LEFT JOIN WH.DIM_AD AS AD
    ON AD.TITULO = N.TITULO AND
        AD.TIPO_ANUNCIO = N.TIPO_ANUNCIO AND
        AD.NOME_VENDEDOR = NULL AND
        AD.CIDADE_VENDEDOR = N.CIDADE_VENDEDOR AND
        AD.ESTADO_VENDEDOR = N.ESTADO_VENDEDOR AND
        AD.UF_VENDEDOR = N.UF_VENDEDOR AND
        AD.BAIRRO = NULL AND
        AD.ENDERECO = NULL AND
        AD.COMPLEMENTO_ENDERECO = NULL AND
        AD.DOCUMENTO_VENDEDOR = NULL AND
        AD.EMAIL = NULL AND
        AD.CELULAR = NULL AND
        AD.TELEFONE = NULL AND
        AD.WHATSAPP = NULL AND
        AD.TIPO_VENDEDOR = N.TIPO_VENDEDOR AND
        AD.VENDEDOR_PJ = NULL AND
        AD.ACEITA_TROCA = N.ACEITA_TROCA AND
        AD.TROCA_COM_TROCO = N.TROCA_COM_TROCO AND
        AD.ENTREGA_CARRO = N.ENTREGA_CARRO AND
        AD.COMENTARIO_DONO = N.COMENTARIO_DONO AND
        AD.PLACA = NULL AND
        AD.LINK_AD = NULL AND
        AD.DATA_CRIACAO_AD = NULL
    LEFT JOIN WH.DIM_CARS AS CARS
    ON CARS.FABRICANTE = N.FABRICANTE AND
        CARS.TIPO_VEICULO = NULL AND
        CARS.MODELO = N.MODELO AND
        CARS.VERSAO = N.VERSAO AND
        CARS.ANO_FABRICACAO = N.ANO_FABRICACAO AND
        CARS.ANO_MODELO = N.ANO_MODELO AND
        CARS.TRANSMISSAO = N.TRANSMISSAO AND
        CARS.QNTD_PORTAS = N.QNTD_PORTAS AND
        CARS.CORPO_VEICULO = N.CORPO_VEICULO AND
        CARS.COR = N.COR AND
        CARS.COR_SECUNDARIA = NULL AND
        CARS.COMBUSTIVEL = N.COMBUSTIVEL AND
        CARS.MOTOR = NULL
    LEFT JOIN WH.DIM_RESOURCES AS RES
    ON RES.FINANCIAVEL = NULL AND
        RES.FINANCIADO = NULL AND
        RES.IMPOSTOS_PAGOS = NULL AND
        RES.REGISTRAMENTO_PAGO = NULL AND
        RES.QUITADO = NULL AND
        RES.ALIENADO = N.ALIENADO AND
        RES.REVISOES_PELA_AGENDA_CARRO = N.REVISOES_PELA_AGENDA_CARRO AND
        RES.REVISOES_PELA_CONCESSIONARIA = N.REVISOES_PELA_CONCESSIONARIA AND
        RES.UNICO_DONO = N.UNICO_DONO AND
        RES.COLECIONADOR = NULL AND
        RES.ADAPTADO_DEFICIENCIA = NULL AND
        RES.BLINDADO = N.BLINDADO AND
        RES.LICENCIADO = N.LICENCIADO AND
        RES.IPVA_PAGO = N.IPVA_PAGO AND
        RES.GARANTIA_DE_FABRICA = N.GARANTIA_DE_FABRICA AND
        RES.AIRBAG = N.AIRBAG AND
        RES.AIRBAG_DUPLO = NULL AND
        RES.ALARME = N.ALARME AND
        RES.AR_CONDICIONADO = N.AR_CONDICIONADO AND
        RES.AR_QUENTE = N.AR_QUENTE AND
        RES.BANCO_REGULA_ALTURA = N.BANCO_REGULA_ALTURA AND
        RES.BANCO_COM_AQUECIMENTO = N.BANCO_COM_AQUECIMENTO AND
        RES.BANCO_DE_COURO = N.BANCO_DE_COURO AND
        RES.CAPOTA_MARITIMA = N.CAPOTA_MARITIMA AND
        RES.MP3_CD_PLAYER = N.MP3_CD_PLAYER AND
        RES.CD_PLAYER = N.CD_PLAYER AND
        RES.DISQUETEIRA = N.DISQUETEIRA AND
        RES.DVD_PLAYER = N.DVD_PLAYER AND
        RES.COMPUTAR_DE_BORDO = N.COMPUTAR_DE_BORDO AND
        RES.CONTROLE_AUTOMATICO_VEL = N.CONTROLE_AUTOMATICO_VEL AND
        RES.CONTROLE_TRACAO = N.CONTROLE_TRACAO AND
        RES.DESEMBACADOR_TRASEIRO = N.DESEMBACADOR_TRASEIRO AND
        RES.DIR_HIDRAULICA = N.DIR_HIDRAULICA AND
        RES.DIR_ELETRICA = NULL AND
        RES.ENCOSTO_CABECA_TRASEIRO = N.ENCOSTO_CABECA_TRASEIRO AND
        RES.FAROL_DE_XENONIO = N.FAROL_DE_XENONIO AND
        RES.FAROL_DE_MILHA = NULL AND
        RES.FAROL_NEBLINA = NULL AND
        RES.FREIO_ABS = N.FREIO_ABS AND
        RES.GPS = N.GPS AND
        RES.LIMPADOR_TRASEIRO = N.LIMPADOR_TRASEIRO AND
        RES.PROTETOR_CACAMBA = N.PROTETOR_CACAMBA AND
        RES.RADIO = N.RADIO AND
        RES.RADIO_TOCAFITA = N.RADIO_TOCAFITA AND
        RES.KIT_MULTIMIDIA = NULL AND
        RES.RETROVISOR_FOTOCROMICO = N.RETROVISOR_FOTOCROMICO AND
        RES.RETROVISOR_ELETRICO = N.RETROVISOR_ELETRICO AND
        RES.RODAS_LIGA_LEVE = N.RODAS_LIGA_LEVE AND
        RES.SENSOR_DE_CHUVA = N.SENSOR_DE_CHUVA AND
        RES.SENSOR_DE_ESTACIONAMENTO = N.SENSOR_DE_ESTACIONAMENTO AND
        RES.TETO_SOLAR = N.TETO_SOLAR AND
        RES.TRACAO_QUATRO_POR_QUATRO = N.TRACAO_QUATRO_POR_QUATRO AND
        RES.TRAVAS_ELETRICAS = N.TRAVAS_ELETRICAS AND
        RES.VIDROS_ELETRICOS = N.VIDROS_ELETRICOS AND
        RES.VOLANTE_REG_ALTURA = N.VOLANTE_REG_ALTURA AND
        RES.PILOTO_AUTOMATICO = NULL AND
        RES.ESCAPAMENTO_ESPORTIVO = NULL
    RETURN NEW;
END;
$BODY$
language plpgsql;

CREATE TRIGGER h
    AFTER INSERT ON STG.WEBMOTORS
    FOR EACH ROW
    EXECUTE FUNCTION webmotors_to_fact();

CREATE TRIGGER g
    AFTER INSERT ON STG.WEBMOTORS
    FOR EACH ROW
    EXECUTE FUNCTION webmotors_to_dim_resources();

CREATE TRIGGER f
    AFTER INSERT ON STG.WEBMOTORS
    FOR EACH ROW
    EXECUTE FUNCTION webmotors_to_dim_cars();

CREATE TRIGGER e
    AFTER INSERT ON STG.WEBMOTORS
    FOR EACH ROW
    EXECUTE FUNCTION webmotors_to_dim_ad();