/* AUTOLINE TRIGGERS */

CREATE OR REPLACE FUNCTION autoline_to_dim_ad() RETURNS TRIGGER AS
$BODY$
BEGIN
    INSERT INTO WH.DIM_AD (
        TITULO,
        TIPO_ANUNCIO,
        NOME_VENDEDOR,
        CIDADE_VENDEDOR,
        ESTADO_VENDEDOR,
        UF_VENDEDOR,
        BAIRRO,
        ENDERECO,
        COMPLEMENTO_ENDERECO,
        DOCUMENTO_VENDEDOR,
        EMAIL,
        CELULAR,
        TELEFONE,
        WHATSAPP,
        TIPO_VENDEDOR,
        VENDEDOR_PJ,
        ACEITA_TROCA,
        TROCA_COM_TROCO,
        ENTREGA_CARRO,
        COMENTARIO_DONO,
        PLACA,
        LINK_AD,
        DATA_CRIACAO_AD
    )
    VALUES(
        NEW.INFORMACOES_ADICIONAIS,
        NULL,
        NEW.NOME_VENDEDOR,
        NEW.CIDADE,
        NEW.ESTADO,
        NEW.UF,
        NEW.BAIRRO,
        NEW.ENDERECO,
        NEW.COMPLEMENTO_ENDERECO,
        NEW.DOCUMENTO_VENDEDOR,
        NEW.EMAIL,
        NEW.CELULAR,
        NEW.TELEFONE,
        NEW.WHATSAPP,
        NEW.TIPO_VENDEDOR,
        NEW.VENDEDOR_PJ,
        NEW.ACEITA_TROCA,
        NULL,
        NULL,
        NULL,
        NEW.PLACA,
        NEW.LINK_AD,
        NEW.DATA_CRIACAO_AD,
    ) ON CONFLICT DO NOTHING;
    RETURN NEW;
END;
$BODY$
language plpgsql;

CREATE OR REPLACE FUNCTION autoline_to_dim_cars() RETURNS TRIGGER AS
$BODY$
BEGIN
    INSERT INTO WH.DIM_CARS (
        FABRICANTE,
        TIPO_VEICULO,
        MODELO,
        VERSAO,
        ANO_FABRICACAO,
        ANO_MODELO,
        TRANSMISSAO,
        QNTD_PORTAS,
        CORPO_VEICULO,
        COR,
        COR_SECUNDARIA,
        COMBUSTIVEL,
        MOTOR,
    ) VALUES (
        NEW.FABRICANTE,
        NEW.TIPO_VEICULO,
        NEW.MODELO,
        NEW.VERSAO,
        NEW.ANO_FABRICACAO,
        NEW.ANO_MODELO,
        NEW.TRANSMISSAO,
        NEW.QNTD_PORTAS,
        NEW.CORPO_VEICULO,
        NEW.COR,
        NEW.COR_SECUNDARIA,
        NEW.COMBUSTIVEL,
        NEW.MOTOR,
    ) ON CONFLICT DO NOTHING;
    RETURN NEW;
END;
$BODY$
language plpgsql;

CREATE OR REPLACE FUNCTION autoline_to_dim_resources() RETURNS TRIGGER AS
$BODY$
BEGIN
    INSERT INTO WH.DIM_RESOURCES (
        FINANCIAVEL,
        FINANCIADO,
        IMPOSTOS_PAGOS,
        REGISTRAMENTO_PAGO,
        QUITADO,
        ALIENADO,
        REVISOES_PELA_AGENDA_CARRO,
        REVISOES_PELA_CONCESSIONARIA,
        UNICO_DONO,
        COLECIONADOR,
        ADAPTADO_DEFICIENCIA,
        BLINDADO,
        LICENCIADO,
        IPVA_PAGO,
        GARANTIA_DE_FABRICA,
        AIRBAG,
        AIRBAG_DUPLO,
        ALARME,
        AR_CONDICIONADO,
        AR_QUENTE,
        BANCO_REGULA_ALTURA,
        BANCO_COM_AQUECIMENTO,
        BANCO_DE_COURO,
        CAPOTA_MARITIMA,
        MP3_CD_PLAYER,
        CD_PLAYER,
        DISQUETEIRA,
        DVD_PLAYER,
        COMPUTAR_DE_BORDO,
        CONTROLE_AUTOMATICO_VEL,
        CONTROLE_TRACAO,
        DESEMBACADOR_TRASEIRO,
        DIR_HIDRAULICA,
        DIR_ELETRICA,
        ENCOSTO_CABECA_TRASEIRO,
        FAROL_DE_XENONIO,
        FAROL_DE_MILHA,
        FAROL_NEBLINA,
        FREIO_ABS,
        GPS,
        LIMPADOR_TRASEIRO,
        PROTETOR_CACAMBA,
        RADIO,
        RADIO_TOCAFITA,
        KIT_MULTIMIDIA,
        RETROVISOR_FOTOCROMICO,
        RETROVISOR_ELETRICO,
        RODAS_LIGA_LEVE,
        SENSOR_DE_CHUVA,
        SENSOR_DE_ESTACIONAMENTO,
        TETO_SOLAR,
        TRACAO_QUATRO_POR_QUATRO,
        TRAVAS_ELETRICAS,
        VIDROS_ELETRICOS,
        VOLANTE_REG_ALTURA,
        PILOTO_AUTOMATICO,
        ESCAPAMENTO_ESPORTIVO
    ) VALUES (
        NEW.FINANCIAVEL,
        NEW.FINANCIADO,
        NEW.IMPOSTOS_PAGOS,
        NEW.REGISTRAMENTO_PAGO,
        NEW.QUITADO,
        NULL,
        NULL,
        NULL,
        NEW.DONO_UNICO,
        NEW.COLECIONADOR,
        NEW.ADAPTADO_DEFICIENCIA,
        NEW.BLINDADO,
        NULL,
        NULL,
        NEW.GARANTIA_DE_FABRICA,
        NEW.AIRBAG,
        NEW.AIRBAG_DUPLO,
        NEW.ALARME,
        NEW.AR_CONDICIONADO,
        NEW.AR_QUENTE,
        NEW.BANCO_REGULA_ALTURA,
        NEW.BANCO_COM_AQUECIMENTO,
        NEW.BANCO_DE_COURO,
        NEW.CAPOTA_MARITIMA,
        NEW.MP3_CD_PLAYER,
        NEW.CD_PLAYER,
        NEW.DISQUETEIRA,
        NEW.DVD_PLAYER,
        NEW.COMPUTAR_DE_BORDO,
        NEW.CONTROLE_AUTOMATICO_VEL,
        NEW.CONTROLE_TRACAO,
        NEW.DESEMBACADOR_TRASEIRO,
        NEW.DIR_HIDRAULICA,
        NEW.DIR_ELETRICA,
        NEW.ENCOSTO_CABECA_TRASEIRO,
        NEW.FAROL_DE_XENONIO,
        NEW.FAROL_DE_MILHA,
        NEW.FAROL_NEBLINA,
        NEW.FREIO_ABS,
        NEW.GPS,
        NEW.LIMPADOR_TRASEIRO,
        NEW.PROTETOR_CACAMBA,
        NEW.RADIO,
        NEW.RADIO_TOCAFITA,
        NEW.KIT_MULTIMIDIA,
        NEW.RETROVISOR_FOTOCROMICO,
        NEW.RETROVISOR_ELETRICO,
        NEW.RODAS_LIGA_LEVE,
        NEW.SENSOR_DE_CHUVA,
        NEW.SENSOR_DE_ESTACIONAMENTO,
        NEW.TETO_SOLAR,
        NEW.TRACAO_QUATRO_POR_QUATRO,
        NEW.TRAVAS_ELETRICAS,
        NEW.VIDROS_ELETRICOS,
        NEW.VOLANTE_REG_ALTURA,
        NEW.PILOTO_AUTOMATICO,
        NEW.ESCAPAMENTO_ESPORTIVO
    ) ON CONFLICT DO NOTHING;
    RETURN NEW;
END;
$BODY$
language plpgsql;

CREATE OR REPLACE FUNCTION autoline_to_fact() RETURNS TRIGGER AS 
$BODY$
BEGIN
    INSERT INTO WH.FACT_AD
    SELECT
        DEFAULT,
        AD.AD_KEY,
        CAR.CAR_KEY,
        RES.RESOURCE_KEY,
        N.KILOMETRAGEM,
        N.PRECO,
        NULL,
        N.PRECO_FIPE
    FROM ( NEW.*) AS N
    LEFT JOIN (
        SELECT
            NEW.COD,
            A.AD_KEY
        FROM WH.DIM_AD AS A
        WHERE 
            A.TITULO = NEW.INFORMACOES_ADICIONAIS AND
            A.TIPO_ANUNCIO = NULL AND
            A.NOME_VENDEDOR = NEW.NOME_VENDEDOR AND
            A.CIDADE_VENDEDOR = NEW.CIDADE AND
            A.ESTADO_VENDEDOR = NEW.ESTADO AND
            A.UF_VENDEDOR = NEW.UF AND
            A.BAIRRO = NEW.BAIRRO AND
            A.ENDERECO = NEW.ENDERECO AND
            A.COMPLEMENTO_ENDERECO = NEW.COMPLEMENTO_ENDERECO AND
            A.DOCUMENTO_VENDEDOR = NEW.DOCUMENTO_VENDEDOR AND
            A.EMAIL = NEW.EMAIL AND
            A.CELULAR = NEW.CELULAR AND
            A.TELEFONE = NEW.TELEFONE AND
            A.WHATSAPP = NEW.WHATSAPP AND
            A.TIPO_VENDEDOR = NEW.TIPO_VENDEDOR AND
            A.VENDEDOR_PJ = NEW.VENDEDOR_PJ AND
            A.ACEITA_TROCA = NEW.ACEITA_TROCA AND
            A.TROCA_COM_TROCO = NULL AND
            A.ENTREGA_CARRO = NULL AND
            A.COMENTARIO_DONO = NULL AND
            A.PLACA = NEW.PLACA AND
            A.LINK_AD = NEW.LINK_AD AND
            A.DATA_CRIACAO_AD = NEW.DATA_CRIACAO_AD
    ) AS AD
    ON N.COD = AD.COD
    LEFT JOIN (
        SELECT
            NEW.COD,
            B.CAR_KEY
        FROM WH.DIM_CARS AS B
        WHERE
            B.FABRICANTE = NEW.FABRICANTE AND
            B.TIPO_VEICULO = NEW.TIPO_VEICULO AND
            B.MODELO = NEW.MODELO AND
            B.VERSAO = NEW.VERSAO AND
            B.ANO_FABRICACAO = NEW.ANO_FABRICACAO AND
            B.ANO_MODELO = NEW.ANO_MODELO AND
            B.TRANSMISSAO = NEW.TRANSMISSAO AND
            B.QNTD_PORTAS = NEW.QNTD_PORTAS AND
            B.CORPO_VEICULO = NEW.CORPO_VEICULO AND
            B.COR = NEW.COR AND
            B.COR_SECUNDARIA = NEW.COR_SECUNDARIA AND
            B.COMBUSTIVEL = NEW.COMBUSTIVEL AND
            B.MOTOR = NEW.MOTOR
    ) AS CAR
    ON N.COD = CAR.COD
    LEFT JOIN (
        SELECT
            NEW.COD,
            C.RESOURCE_KEY
        FROM WH.DIM_RESOURCES AS C
        WHERE
            C.FINANCIAVEL = NEW.FINANCIAVEL AND
            C.FINANCIADO = NEW.FINANCIADO AND
            C.IMPOSTOS_PAGOS = NEW.IMPOSTOS_PAGOS AND
            C.REGISTRAMENTO_PAGO = NEW.REGISTRAMENTO_PAGO AND
            C.QUITADO = NEW.QUITADO AND
            C.ALIENADO = NULL AND
            C.REVISOES_PELA_AGENDA_CARRO = NULL AND
            C.REVISOES_PELA_CONCESSIONARIA = NULL AND
            C.UNICO_DONO = NEW.DONO_UNICO AND
            C.COLECIONADOR = NEW.COLECIONADOR AND
            C.ADAPTADO_DEFICIENCIA = NEW.ADAPTADO_DEFICIENCIA AND
            C.BLINDADO = NEW.BLINDADO AND
            C.LICENCIADO = NULL AND
            C.IPVA_PAGO = NULL AND
            C.GARANTIA_DE_FABRICA = NEW.GARANTIA_DE_FABRICA AND
            C.AIRBAG = NEW.AIRBAG AND
            C.AIRBAG_DUPLO = NEW.AIRBAG_DUPLO AND
            C.ALARME = NEW.ALARME AND
            C.AR_CONDICIONADO = NEW.AR_CONDICIONADO AND
            C.AR_QUENTE = NEW.AR_QUENTE AND
            C.BANCO_REGULA_ALTURA = NEW.BANCO_REGULA_ALTURA AND
            C.BANCO_COM_AQUECIMENTO = NEW.BANCO_COM_AQUECIMENTO AND
            C.BANCO_DE_COURO = NEW.BANCO_DE_COURO AND
            C.CAPOTA_MARITIMA = NEW.CAPOTA_MARITIMA AND
            C.MP3_CD_PLAYER = NEW.MP3_CD_PLAYER AND
            C.CD_PLAYER = NEW.CD_PLAYER AND
            C.DISQUETEIRA = NEW.DISQUETEIRA AND
            C.DVD_PLAYER = NEW.DVD_PLAYER AND
            C.COMPUTAR_DE_BORDO = NEW.COMPUTAR_DE_BORDO AND
            C.CONTROLE_AUTOMATICO_VEL = NEW.CONTROLE_AUTOMATICO_VEL AND
            C.CONTROLE_TRACAO = NEW.CONTROLE_TRACAO AND
            C.DESEMBACADOR_TRASEIRO = NEW.DESEMBACADOR_TRASEIRO AND
            C.DIR_HIDRAULICA = NEW.DIR_HIDRAULICA AND
            C.DIR_ELETRICA = NEW.DIR_ELETRICA AND
            C.ENCOSTO_CABECA_TRASEIRO = NEW.ENCOSTO_CABECA_TRASEIRO AND
            C.FAROL_DE_XENONIO = NEW.FAROL_DE_XENONIO AND
            C.FAROL_DE_MILHA = NEW.FAROL_DE_MILHA AND
            C.FAROL_NEBLINA = NEW.FAROL_NEBLINA AND
            C.FREIO_ABS = NEW.FREIO_ABS AND
            C.GPS = NEW.GPS AND
            C.LIMPADOR_TRASEIRO = NEW.LIMPADOR_TRASEIRO AND
            C.PROTETOR_CACAMBA = NEW.PROTETOR_CACAMBA AND
            C.RADIO = NEW.RADIO AND
            C.RADIO_TOCAFITA = NEW.RADIO_TOCAFITA AND
            C.KIT_MULTIMIDIA = NEW.KIT_MULTIMIDIA AND
            C.RETROVISOR_FOTOCROMICO = NEW.RETROVISOR_FOTOCROMICO AND
            C.RETROVISOR_ELETRICO = NEW.RETROVISOR_ELETRICO AND
            C.RODAS_LIGA_LEVE = NEW.RODAS_LIGA_LEVE AND
            C.SENSOR_DE_CHUVA = NEW.SENSOR_DE_CHUVA AND
            C.SENSOR_DE_ESTACIONAMENTO = NEW.SENSOR_DE_ESTACIONAMENTO AND
            C.TETO_SOLAR = NEW.TETO_SOLAR AND
            C.TRACAO_QUATRO_POR_QUATRO = NEW.TRACAO_QUATRO_POR_QUATRO AND
            C.TRAVAS_ELETRICAS = NEW.TRAVAS_ELETRICAS AND
            C.VIDROS_ELETRICOS = NEW.VIDROS_ELETRICOS AND
            C.VOLANTE_REG_ALTURA = NEW.VOLANTE_REG_ALTURA AND
            C.PILOTO_AUTOMATICO = NEW.PILOTO_AUTOMATICO AND
            C.ESCAPAMENTO_ESPORTIV = NEW.ESCAPAMENTO_ESPORTIVO
    ) AS RES
    ON N.COD = RES.COD;
    RETURN NEW;
END;
$BODY$
language plpgsql;

CREATE OR REPLACE FUNCTION autoline_execute_moves() RETURNS TRIGGER AS 
$BODY$
BEGIN
    PERFORM autoline_to_dim_ad();
    PERFORM autoline_to_dim_cars();
    PERFORM autoline_to_dim_resources();
    PERFORM autoline_to_fact();
END;
$BODY$
language plpgsql;

CREATE TRIGGER autoline_stg_to_star
    AFTER INSERT ON STG.AUTOLINE
    FOR EACH ROW
    EXECUTE PROCEDURE autoline_execute_moves();

/* WEBMOTORS TRIGGERS */

CREATE OR REPLACE FUNCTION webmotors_to_dim_ad() RETURNS TRIGGER AS
$BODY$
BEGIN
    INSERT INTO WH.DIM_AD (
        TITULO,
        TIPO_ANUNCIO,
        NOME_VENDEDOR,
        CIDADE_VENDEDOR,
        ESTADO_VENDEDOR,
        UF_VENDEDOR,
        BAIRRO,
        ENDERECO,
        COMPLEMENTO_ENDERECO,
        DOCUMENTO_VENDEDOR,
        EMAIL,
        CELULAR,
        TELEFONE,
        WHATSAPP,
        TIPO_VENDEDOR,
        VENDEDOR_PJ,
        ACEITA_TROCA,
        TROCA_COM_TROCO,
        ENTREGA_CARRO,
        COMENTARIO_DONO,
        PLACA,
        LINK_AD,
        DATA_CRIACAO_AD
    ) VALUES (
        NEW.TITULO,
        NEW.TIPO_ANUNCIO,
        NULL,
        NEW.CIDADE_VENDEDOR,
        NEW.ESTADO_VENDEDOR,
        NEW.UF_VENDEDOR,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NEW.TIPO_VENDEDOR,
        NULL,
        NEW.ACEITA_TROCA,
        NEW.TROCA_COM_TROCO,
        NEW.ENTREGA_CARRO,
        NEW.COMENTARIO_DONO,
        NULL,
        NULL,
        NULL
    ) ON CONFLICT DO NOTHING;
    RETURN NEW;
END;
$BODY$
language plpgsql;

CREATE OR REPLACE FUNCTION webmotors_to_dim_cars() RETURNS TRIGGER AS
$BODY$
BEGIN
    INSERT INTO WH.DIM_CARS (
        FABRICANTE,
        TIPO_VEICULO,
        MODELO,
        VERSAO,
        ANO_FABRICACAO,
        ANO_MODELO,
        TRANSMISSAO,
        QNTD_PORTAS,
        CORPO_VEICULO,
        COR,
        COR_SECUNDARIA,
        COMBUSTIVEL,
        MOTOR,
    ) VALUES (
        NEW.FABRICANTE,
        NULL,
        NEW.MODELO,
        NEW.VERSAO,
        NEW.ANO_FABRICACAO,
        NEW.ANO_MODELO,
        NEW.TRANSMISSAO,
        NEW.QNTD_PORTAS,
        NEW.CORPO_VEICULO,
        NEW.COR,
        NULL,
        NEW.COMBUSTIVEL,
        NULL,
    ) ON CONFLICT DO NOTHING;
    RETURN NEW;
END;
$BODY$
language plpgsql;

CREATE OR REPLACE FUNCTION webmotors_to_dim_resources() RETURNS TRIGGER AS
$BODY$
BEGIN
    INSERT INTO WH.DIM_RESOURCES (
        FINANCIAVEL,
        FINANCIADO,
        IMPOSTOS_PAGOS,
        REGISTRAMENTO_PAGO,
        QUITADO,
        ALIENADO,
        REVISOES_PELA_AGENDA_CARRO,
        REVISOES_PELA_CONCESSIONARIA,
        UNICO_DONO,
        COLECIONADOR,
        ADAPTADO_DEFICIENCIA,
        BLINDADO,
        LICENCIADO,
        IPVA_PAGO,
        GARANTIA_DE_FABRICA,
        AIRBAG,
        AIRBAG_DUPLO,
        ALARME,
        AR_CONDICIONADO,
        AR_QUENTE,
        BANCO_REGULA_ALTURA,
        BANCO_COM_AQUECIMENTO,
        BANCO_DE_COURO,
        CAPOTA_MARITIMA,
        MP3_CD_PLAYER,
        CD_PLAYER,
        DISQUETEIRA,
        DVD_PLAYER,
        COMPUTAR_DE_BORDO,
        CONTROLE_AUTOMATICO_VEL,
        CONTROLE_TRACAO,
        DESEMBACADOR_TRASEIRO,
        DIR_HIDRAULICA,
        DIR_ELETRICA,
        ENCOSTO_CABECA_TRASEIRO,
        FAROL_DE_XENONIO,
        FAROL_DE_MILHA,
        FAROL_NEBLINA,
        FREIO_ABS,
        GPS,
        LIMPADOR_TRASEIRO,
        PROTETOR_CACAMBA,
        RADIO,
        RADIO_TOCAFITA,
        KIT_MULTIMIDIA,
        RETROVISOR_FOTOCROMICO,
        RETROVISOR_ELETRICO,
        RODAS_LIGA_LEVE,
        SENSOR_DE_CHUVA,
        SENSOR_DE_ESTACIONAMENTO,
        TETO_SOLAR,
        TRACAO_QUATRO_POR_QUATRO,
        TRAVAS_ELETRICAS,
        VIDROS_ELETRICOS,
        VOLANTE_REG_ALTURA,
        PILOTO_AUTOMATICO,
        ESCAPAMENTO_ESPORTIVO
    ) VALUES (
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NEW.ALIENADO,
        NEW.REVISOES_PELA_AGENDA_CARRO,
        NEW.REVISOES_PELA_CONCESSIONARIA,
        NEW.UNICO_DONO,
        NULL,
        NULL,
        NEW.BLINDADO,
        NEW.LICENCIADO,
        NEW.IPVA_PAGO,
        NEW.GARANTIA_DE_FABRICA,
        NEW.AIRBAG,
        NULL,
        NEW.ALARME,
        NEW.AR_CONDICIONADO,
        NEW.AR_QUENTE,
        NEW.BANCO_REGULA_ALTURA,
        NEW.BANCO_COM_AQUECIMENTO,
        NEW.BANCO_DE_COURO,
        NEW.CAPOTA_MARITIMA,
        NEW.MP3_CD_PLAYER,
        NEW.CD_PLAYER,
        NEW.DISQUETEIRA,
        NEW.DVD_PLAYER,
        NEW.COMPUTAR_DE_BORDO,
        NEW.CONTROLE_AUTOMATICO_VEL,
        NEW.CONTROLE_TRACAO,
        NEW.DESEMBACADOR_TRASEIRO,
        NEW.DIR_HIDRAULICA,
        NULL,
        NEW.ENCOSTO_CABECA_TRASEIRO,
        NEW.FAROL_DE_XENONIO,
        NULL,
        NULL,
        NEW.FREIO_ABS,
        NEW.GPS,
        NEW.LIMPADOR_TRASEIRO,
        NEW.PROTETOR_CACAMBA,
        NEW.RADIO,
        NEW.RADIO_TOCAFITA,
        NULL,
        NEW.RETROVISOR_FOTOCROMICO,
        NEW.RETROVISOR_ELETRICO,
        NEW.RODAS_LIGA_LEVE,
        NEW.SENSOR_DE_CHUVA,
        NEW.SENSOR_DE_ESTACIONAMENTO,
        NEW.TETO_SOLAR,
        NEW.TRACAO_QUATRO_POR_QUATRO,
        NEW.TRAVAS_ELETRICAS,
        NEW.VIDROS_ELETRICOS,
        NEW.VOLANTE_REG_ALTURA,
        NULL,
        NULL
    ) ON CONFLICT DO NOTHING;
    RETURN NEW;
END;
$BODY$
language plpgsql;

CREATE OR REPLACE FUNCTION webmotors_to_fact() RETURNS TRIGGER AS 
$BODY$
BEGIN
    INSERT INTO WH.FACT_AD
    SELECT
        DEFAULT,
        AD.AD_KEY,
        CAR.CAR_KEY,
        RES.RESOURCE_KEY,
        N.KILOMETRAGEM,
        N.PRECO,
        N.PRECO_DESEJADO,
        N.PORCENTAGEM_FIPE
    FROM ( NEW.* ) AS N
    LEFT JOIN (
        SELECT
            NEW.COD,
            A.AD_KEY
        FROM WH.DIM_AD AS A
        WHERE 
            A.TITULO = NEW.TITULO AND
            A.TIPO_ANUNCIO = NEW.TIPO_ANUNCIO AND
            A.NOME_VENDEDOR = NULL AND
            A.CIDADE_VENDEDOR = NEW.CIDADE_VENDEDOR AND
            A.ESTADO_VENDEDOR = NEW.ESTADO_VENDEDOR AND
            A.UF_VENDEDOR = NEW.UF_VENDEDOR AND
            A.BAIRRO = NULL AND
            A.ENDERECO = NULL AND
            A.COMPLEMENTO_ENDERECO = NULL AND
            A.DOCUMENTO_VENDEDOR = NULL AND
            A.EMAIL = NULL AND
            A.CELULAR = NULL AND
            A.TELEFONE = NULL AND
            A.WHATSAPP = NULL AND
            A.TIPO_VENDEDOR = NEW.TIPO_VENDEDOR AND
            A.VENDEDOR_PJ = NULL AND
            A.ACEITA_TROCA = NEW.ACEITA_TROCA AND
            A.TROCA_COM_TROCO = NEW.TROCA_COM_TROCO AND
            A.ENTREGA_CARRO = NEW.ENTREGA_CARRO AND
            A.COMENTARIO_DONO = NEW.COMENTARIO_DONO AND
            A.PLACA = NULL AND
            A.LINK_AD = NULL AND
            A.DATA_CRIACAO_AD = NULL
    ) AS AD
    ON N.COD = AD.COD
    LEFT JOIN (
        SELECT
            NEW.COD,
            B.CAR_KEY
        FROM WH.DIM_CARS AS B
        WHERE
            B.FABRICANTE = NEW.FABRICANTE AND
            B.TIPO_VEICULO = NULL AND
            B.MODELO = NEW.MODELO AND
            B.VERSAO = NEW.VERSAO AND
            B.ANO_FABRICACAO = NEW.ANO_FABRICACAO AND
            B.ANO_MODELO = NEW.ANO_MODELO AND
            B.TRANSMISSAO = NEW.TRANSMISSAO AND
            B.QNTD_PORTAS = NEW.QNTD_PORTAS AND
            B.CORPO_VEICULO = NEW.CORPO_VEICULO AND
            B.COR = NEW.COR AND
            B.COR_SECUNDARIA = NULL AND
            B.COMBUSTIVEL = NEW.COMBUSTIVEL AND
            B.MOTOR = NULL
    ) AS CAR
    ON N.COD = CAR.COD
    LEFT JOIN (
        SELECT
            NEW.COD,
            C.RESOURCE_KEY
        FROM WH.DIM_RESOURCES AS C
        WHERE
            C.FINANCIAVEL = NULL AND
            C.FINANCIADO = NULL AND
            C.IMPOSTOS_PAGOS = NULL AND
            C.REGISTRAMENTO_PAGO = NULL AND
            C.QUITADO = NULL AND
            C.ALIENADO = NEW.ALIENADO AND
            C.REVISOES_PELA_AGENDA_CARRO = NEW.REVISOES_PELA_AGENDA_CARRO AND
            C.REVISOES_PELA_CONCESSIONARIA = NEW.REVISOES_PELA_CONCESSIONARIA AND
            C.UNICO_DONO = NEW.UNICO_DONO AND
            C.COLECIONADOR = NULL AND
            C.ADAPTADO_DEFICIENCIA = NULL AND
            C.BLINDADO = NEW.BLINDADO AND
            C.LICENCIADO = NEW.LICENCIADO AND
            C.IPVA_PAGO = NEW.IPVA_PAGO AND
            C.GARANTIA_DE_FABRICA = NEW.GARANTIA_DE_FABRICA AND
            C.AIRBAG = NEW.AIRBAG AND
            C.AIRBAG_DUPLO = NULL AND
            C.ALARME = NEW.ALARME AND
            C.AR_CONDICIONADO = NEW.AR_CONDICIONADO AND
            C.AR_QUENTE = NEW.AR_QUENTE AND
            C.BANCO_REGULA_ALTURA = NEW.BANCO_REGULA_ALTURA AND
            C.BANCO_COM_AQUECIMENTO = NEW.BANCO_COM_AQUECIMENTO AND
            C.BANCO_DE_COURO = NEW.BANCO_DE_COURO AND
            C.CAPOTA_MARITIMA = NEW.CAPOTA_MARITIMA AND
            C.MP3_CD_PLAYER = NEW.MP3_CD_PLAYER AND
            C.CD_PLAYER = NEW.CD_PLAYER AND
            C.DISQUETEIRA = NEW.DISQUETEIRA AND
            C.DVD_PLAYER = NEW.DVD_PLAYER AND
            C.COMPUTAR_DE_BORDO = NEW.COMPUTAR_DE_BORDO AND
            C.CONTROLE_AUTOMATICO_VEL = NEW.CONTROLE_AUTOMATICO_VEL AND
            C.CONTROLE_TRACAO = NEW.CONTROLE_TRACAO AND
            C.DESEMBACADOR_TRASEIRO = NEW.DESEMBACADOR_TRASEIRO AND
            C.DIR_HIDRAULICA = NEW.DIR_HIDRAULICA AND
            C.DIR_ELETRICA = NULL AND
            C.ENCOSTO_CABECA_TRASEIRO = NEW.ENCOSTO_CABECA_TRASEIRO AND
            C.FAROL_DE_XENONIO = NEW.FAROL_DE_XENONIO AND
            C.FAROL_DE_MILHA = NULL AND
            C.FAROL_NEBLINA = NULL AND
            C.FREIO_ABS = NEW.FREIO_ABS AND
            C.GPS = NEW.GPS AND
            C.LIMPADOR_TRASEIRO = NEW.LIMPADOR_TRASEIRO AND
            C.PROTETOR_CACAMBA = NEW.PROTETOR_CACAMBA AND
            C.RADIO = NEW.RADIO AND
            C.RADIO_TOCAFITA = NEW.RADIO_TOCAFITA AND
            C.KIT_MULTIMIDIA = NULL AND
            C.RETROVISOR_FOTOCROMICO = NEW.RETROVISOR_FOTOCROMICO AND
            C.RETROVISOR_ELETRICO = NEW.RETROVISOR_ELETRICO AND
            C.RODAS_LIGA_LEVE = NEW.RODAS_LIGA_LEVE AND
            C.SENSOR_DE_CHUVA = NEW.SENSOR_DE_CHUVA AND
            C.SENSOR_DE_ESTACIONAMENTO = NEW.SENSOR_DE_ESTACIONAMENTO AND
            C.TETO_SOLAR = NEW.TETO_SOLAR AND
            C.TRACAO_QUATRO_POR_QUATRO = NEW.TRACAO_QUATRO_POR_QUATRO AND
            C.TRAVAS_ELETRICAS = NEW.TRAVAS_ELETRICAS AND
            C.VIDROS_ELETRICOS = NEW.VIDROS_ELETRICOS AND
            C.VOLANTE_REG_ALTURA = NEW.VOLANTE_REG_ALTURA AND
            C.PILOTO_AUTOMATICO = NULL AND
            C.ESCAPAMENTO_ESPORTIVO = NULL
    ) AS RES
    ON N.COD = RES.COD
    RETURN NEW;
END;
$BODY$
language plpgsql;

CREATE OR REPLACE FUNCTION webmotors_execute_moves() RETURNS TRIGGER AS 
$BODY$
BEGIN
    PERFORM webmotors_to_dim_ad();
    PERFORM webmotors_to_dim_cars();
    PERFORM webmotors_to_dim_resources();
    PERFORM webmotors_to_fact();
END;
$BODY$
language plpgsql;

CREATE TRIGGER webmotors_stg_to_star
    AFTER INSERT ON STG.WEBMOTORS
    FOR EACH ROW
    EXECUTE PROCEDURE webmotors_execute_moves();