INSERT INTO WH.DIM_CAR (
    FABRICANTE,
    TIPO_VEICULO,
    MODELO,
    VERSAO,
    ANO_FABRICACAO,
    ANO_MODELO,
    TRANSMISSAO,
    QNTD_PORTAS,
    CORPO_VEICULO,
    COR,
    COR_SECUNDARIA,
    COMBUSTIVEL,
    MOTOR,
    PLACA
) SELECT DISTINCT
    A.FABRICANTE,
    A.TIPO_VEICULO,
    A.MODELO,
    A.VERSAO,
    A.ANO_FABRICACAO,
    A.ANO_MODELO,
    A.TRANSMISSAO,
    A.QNTD_PORTAS,
    A.CORPO_VEICULO,
    A.COR,
    A.COR_SECUNDARIA,
    A.COMBUSTIVEL,
    A.MOTOR,
    A.PLACA
FROM STG.AUTOLINE AS A;

UPDATE STG.AUTOLINE
SET STG.AUTOLINE.CAR_KEY = WH.DIM_CAR.CAR_KEY
FROM STG.AUTOLINE
INNER JOIN WH.DIM_CAR ON 
WH.DIM_AD.FABRICANTE = STG.AUTOLINE.FABRICANTE AND
WH.DIM_AD.TIPO_VEICULO = STG.AUTOLINE.TIPO_VEICULO AND
WH.DIM_AD.MODELO = STG.AUTOLINE.MODELO AND
WH.DIM_AD.VERSAO = STG.AUTOLINE.VERSAO AND
WH.DIM_AD.ANO_FABRICACAO = STG.AUTOLINE.ANO_FABRICACAO AND
WH.DIM_AD.ANO_MODELO = STG.AUTOLINE.ANO_MODELO AND
WH.DIM_AD.TRANSMISSAO = STG.AUTOLINE.TRANSMISSAO AND
WH.DIM_AD.QNTD_PORTAS = STG.AUTOLINE.QNTD_PORTAS AND
WH.DIM_AD.CORPO_VEICULO = STG.AUTOLINE.CORPO_VEICULO AND
WH.DIM_AD.COR = STG.AUTOLINE.COR AND
WH.DIM_AD.COR_SECUNDARIA = STG.AUTOLINE.COR_SECUNDARIA AND
WH.DIM_AD.COMBUSTIVEL = STG.AUTOLINE.COMBUSTIVEL AND
WH.DIM_AD.MOTOR = STG.AUTOLINE.MOTOR AND
WH.DIM_AD.PLACA = STG.AUTOLINE.PLACA AND;