INSERT INTO WH.DIM_AD (
    AD_ID,
    TITULO,
    TIPO_ANUNCIO,
    ACEITA_TROCA,
    TROCA_COM_TROCO,
    ENTREGA_CARRO,
    COMENTARIO_DONO,
    WEBSITE
) SELECT DISTINCT
    A.AD_ID,
    A.TITULO,
    A.TIPO_ANUNCIO,
    A.ACEITA_TROCA,
    A.TROCA_COM_TROCO,
    A.ENTREGA_CARRO,
    A.COMENTARIO_DONO,
    A.WEBSITE
FROM STG.WEBMOTORS AS A;

UPDATE STG.WEBMOTORS
SET STG.WEBMOTORS.AD_KEY = WH.DIM_AD.AD_KEY
FROM STG.WEBMOTORS
INNER JOIN WH.DIM_AD ON 
WH.DIM_AD.AD_ID = STG.WEBMOTORS.AD_ID AND
WH.DIM_AD.TITULO = STG.WEBMOTORS.TITULO AND
WH.DIM_AD.TIPO_ANUNCIO = STG.WEBMOTORS.TIPO_ANUNCIO AND
WH.DIM_AD.ACEITA_TROCA = STG.WEBMOTORS.ACEITA_TROCA AND
WH.DIM_AD.TROCA_COM_TROCO = STG.WEBMOTORS.TROCA_COM_TROCO AND
WH.DIM_AD.ENTREGA_CARRO = STG.WEBMOTORS.ENTREGA_CARRO AND
WH.DIM_AD.COMENTARIO_DONO = STG.WEBMOTORS.COMENTARIO_DONO  AND
WH.DIM_AD.WEBSITE = STG.WEBMOTORS.WEBSITE AND;