INSERT INTO WH.DIM_CAR (
    FABRICANTE,
    MODELO,
    VERSAO,
    ANO_FABRICACAO,
    ANO_MODELO,
    TRANSMISSAO,
    QNTD_PORTAS,
    CORPO_VEICULO,
    COR,
    COMBUSTIVEL
) SELECT DISTINCT
    A.FABRICANTE,
    A.MODELO,
    A.VERSAO,
    A.ANO_FABRICACAO,
    A.ANO_MODELO,
    A.TRANSMISSAO,
    A.QNTD_PORTAS,
    A.CORPO_VEICULO,
    A.COR,
    A.COMBUSTIVEL,
FROM STG.WEBMOTORS AS A;

UPDATE STG.WEBMOTORS
SET STG.WEBMOTORS.CAR_KEY = WH.DIM_CAR.CAR_KEY
FROM STG.WEBMOTORS
INNER JOIN WH.DIM_CAR ON 
WH.DIM_CAR.FABRICANTE = STG.WEBMOTORS.FABRICANTE AND
WH.DIM_CAR.TIPO_VEICULO = 'INDISPONIVEL' AND
WH.DIM_CAR.MODELO = STG.WEBMOTORS.MODELO AND
WH.DIM_CAR.VERSAO = STG.WEBMOTORS.VERSAO AND
WH.DIM_CAR.ANO_FABRICACAO = STG.WEBMOTORS.ANO_FABRICACAO AND
WH.DIM_CAR.ANO_MODELO = STG.WEBMOTORS.ANO_MODELO AND
WH.DIM_CAR.TRANSMISSAO = STG.WEBMOTORS.TRANSMISSAO AND
WH.DIM_CAR.QNTD_PORTAS = STG.WEBMOTORS.QNTD_PORTAS AND
WH.DIM_CAR.CORPO_VEICULO = STG.WEBMOTORS.CORPO_VEICULO AND
WH.DIM_CAR.COR = STG.WEBMOTORS.COR AND
WH.DIM_CAR.COR_SECUNDARIA = 'INDISPONIVEL' AND
WH.DIM_CAR.COMBUSTIVEL = STG.WEBMOTORS.COMBUSTIVEL AND
WH.DIM_CAR.MOTOR = 'INDISPONIVEL' AND
WH.DIM_CAR.PLACA = 'INDISPONIVEL';