INSERT INTO WH.DIM_SELLER (
    TIPO_VENDEDOR
) SELECT DISTINCT
    A.TIPO_VENDEDOR
FROM STG.WEBMOTORS AS A;

UPDATE STG.WEBMOTORS
SET STG.WEBMOTORS.SELLER_KEY = WH.DIM_SELLER.SELLER_KEY
FROM STG.WEBMOTORS
INNER JOIN WH.DIM_SELLER ON 
WH.DIM_AD.NOME_VENDEDOR = 'false'  AND
WH.DIM_AD.DOCUMENTO_VENDEDOR = 'false'  AND
WH.DIM_AD.EMAIL = 'false'  AND
WH.DIM_AD.CELULAR = 'false'  AND
WH.DIM_AD.TELEFONE = 'false'  AND
WH.DIM_AD.WHATSAPP = 'false'  AND
WH.DIM_AD.TIPO_VENDEDOR = STG.WEBMOTORS.TIPO_VENDEDOR AND
WH.DIM_AD.VENDEDOR_PJ = 'false' AND;