INSERT INTO WH.DIM_RESOURCE (
    ALIENADO,
    REVISOES_PELA_AGENDA_CARRO,
    REVISOES_PELA_CONCESSIONARIA,
    UNICO_DONO,
    BLINDADO,
    LICENCIADO,
    IPVA_PAGO,
    GARANTIA_DE_FABRICA,
    AIRBAG,
    ALARME,
    AR_CONDICIONADO,
    AR_QUENTE,
    BANCO_REGULA_ALTURA,
    BANCO_COM_AQUECIMENTO,
    BANCO_DE_COURO,
    CAPOTA_MARITIMA,
    MP3_CD_PLAYER,
    CD_PLAYER,
    DISQUETEIRA,
    DVD_PLAYER,
    COMPUTAR_DE_BORDO,
    CONTROLE_AUTOMATICO_VEL,
    CONTROLE_TRACAO,
    DESEMBACADOR_TRASEIRO,
    DIR_HIDRAULICA,
    ENCOSTO_CABECA_TRASEIRO,
    FAROL_DE_XENONIO,
    FREIO_ABS,
    GPS,
    LIMPADOR_TRASEIRO,
    PROTETOR_CACAMBA,
    RADIO,
    RADIO_TOCAFITA,
    RETROVISOR_FOTOCROMICO,
    RETROVISOR_ELETRICO,
    RODAS_LIGA_LEVE,
    SENSOR_DE_CHUVA,
    SENSOR_DE_ESTACIONAMENTO,
    TETO_SOLAR,
    TRACAO_QUATRO_POR_QUATRO,
    TRAVAS_ELETRICAS,
    VIDROS_ELETRICOS,
    VOLANTE_REG_ALTURA,
) SELECT DISTINCT
    A.ALIENADO,
    A.REVISOES_PELA_AGENDA_CARRO,
    A.REVISOES_PELA_CONCESSIONARIA,
    A.UNICO_DONO,
    A.BLINDADO,
    A.LICENCIADO,
    A.IPVA_PAGO,
    A.GARANTIA_DE_FABRICA,
    A.AIRBAG,
    A.ALARME,
    A.AR_CONDICIONADO,
    A.AR_QUENTE,
    A.BANCO_REGULA_ALTURA,
    A.BANCO_COM_AQUECIMENTO,
    A.BANCO_DE_COURO,
    A.CAPOTA_MARITIMA,
    A.MP3_CD_PLAYER,
    A.CD_PLAYER,
    A.DISQUETEIRA,
    A.DVD_PLAYER,
    A.COMPUTAR_DE_BORDO,
    A.CONTROLE_AUTOMATICO_VEL,
    A.CONTROLE_TRACAO,
    A.DESEMBACADOR_TRASEIRO,
    A.DIR_HIDRAULICA,
    A.ENCOSTO_CABECA_TRASEIRO,
    A.FAROL_DE_XENONIO,
    A.FREIO_ABS,
    A.GPS,
    A.LIMPADOR_TRASEIRO,
    A.PROTETOR_CACAMBA,
    A.RADIO,
    A.RADIO_TOCAFITA,
    A.RETROVISOR_FOTOCROMICO,
    A.RETROVISOR_ELETRICO,
    A.RODAS_LIGA_LEVE,
    A.SENSOR_DE_CHUVA,
    A.SENSOR_DE_ESTACIONAMENTO,
    A.TETO_SOLAR,
    A.TRACAO_QUATRO_POR_QUATRO,
    A.TRAVAS_ELETRICAS,
    A.VIDROS_ELETRICOS,
    A.VOLANTE_REG_ALTURA
FROM STG.WEBMOTORS AS A;

UPDATE STG.WEBMOTORS
SET STG.WEBMOTORS.RESOURCE_KEY = WH.DIM_RESOURCE.RESOURCE_KEY
FROM STG.WEBMOTORS
INNER JOIN WH.DIM_RESOURCE ON 
    WH.DIM_RESOURCE.FINANCIAVEL = 'false' AND
    WH.DIM_RESOURCE.FINANCIADO = 'false' AND
    WH.DIM_RESOURCE.IMPOSTOS_PAGOS = 'false' AND
    WH.DIM_RESOURCE.REGISTRAMENTO_PAGO = 'false' AND
    WH.DIM_RESOURCE.QUITADO = 'false' AND
    WH.DIM_RESOURCE.ALIENADO = STG.WEBMOTORS.ALIENADO AND
    WH.DIM_RESOURCE.REVISOES_PELA_AGENDA_CARRO = STG.WEBMOTORS.REVISOES_PELA_AGENDA_CARRO AND
    WH.DIM_RESOURCE.REVISOES_PELA_CONCESSIONARIA = STG.WEBMOTORS.REVISOES_PELA_CONCESSIONARIA AND
    WH.DIM_RESOURCE.UNICO_DONO = STG.WEBMOTORS.UNICO_DONO AND
    WH.DIM_RESOURCE.COLECIONADOR = 'false'AND
    WH.DIM_RESOURCE.ADAPTADO_DEFICIENCIA = 'false' AND
    WH.DIM_RESOURCE.BLINDADO = STG.WEBMOTORS.BLINDADO AND
    WH.DIM_RESOURCE.LICENCIADO = STG.WEBMOTORS.LICENCIADO AND
    WH.DIM_RESOURCE.IPVA_PAGO = STG.WEBMOTORS.IPVA_PAGO  AND
    WH.DIM_RESOURCE.GARANTIA_DE_FABRICA = STG.WEBMOTORS.GARANTIA_DE_FABRICA AND
    WH.DIM_RESOURCE.AIRBAG = STG.WEBMOTORS.AIRBAG AND
    WH.DIM_RESOURCE.AIRBAG_DUPLO = 'false' AND
    WH.DIM_RESOURCE.ALARME = STG.WEBMOTORS.ALARME AND
    WH.DIM_RESOURCE.AR_CONDICIONADO = STG.WEBMOTORS.AR_CONDICIONADO AND
    WH.DIM_RESOURCE.AR_QUENTE = STG.WEBMOTORS.AR_QUENTE AND
    WH.DIM_RESOURCE.BANCO_REGULA_ALTURA = STG.WEBMOTORS.BANCO_REGULA_ALTURA AND
    WH.DIM_RESOURCE.BANCO_COM_AQUECIMENTO = STG.WEBMOTORS.BANCO_COM_AQUECIMENTO AND
    WH.DIM_RESOURCE.BANCO_DE_COURO = STG.WEBMOTORS.BANCO_DE_COURO AND
    WH.DIM_RESOURCE.CAPOTA_MARITIMA = STG.WEBMOTORS.CAPOTA_MARITIMA AND
    WH.DIM_RESOURCE.MP3_CD_PLAYER = STG.WEBMOTORS.MP3_CD_PLAYER AND
    WH.DIM_RESOURCE.CD_PLAYER = STG.WEBMOTORS.CD_PLAYER AND
    WH.DIM_RESOURCE.DISQUETEIRA = STG.WEBMOTORS.DISQUETEIRA AND
    WH.DIM_RESOURCE.DVD_PLAYER = STG.WEBMOTORS.DVD_PLAYER AND
    WH.DIM_RESOURCE.COMPUTAR_DE_BORDO = STG.WEBMOTORS.COMPUTAR_DE_BORDO AND
    WH.DIM_RESOURCE.CONTROLE_AUTOMATICO_VEL = STG.WEBMOTORS.CONTROLE_AUTOMATICO_VEL AND
    WH.DIM_RESOURCE.CONTROLE_TRACAO = STG.WEBMOTORS.CONTROLE_TRACAO AND
    WH.DIM_RESOURCE.DESEMBACADOR_TRASEIRO = STG.WEBMOTORS.DESEMBACADOR_TRASEIRO AND
    WH.DIM_RESOURCE.DIR_HIDRAULICA = STG.WEBMOTORS.DIR_HIDRAULICA AND
    WH.DIM_RESOURCE.DIR_ELETRICA = 'false'AND
    WH.DIM_RESOURCE.ENCOSTO_CABECA_TRASEIRO = STG.WEBMOTORS.ENCOSTO_CABECA_TRASEIRO AND
    WH.DIM_RESOURCE.FAROL_DE_XENONIO = STG.WEBMOTORS.FAROL_DE_XENONIO AND
    WH.DIM_RESOURCE.FAROL_DE_MILHA = 'false' AND
    WH.DIM_RESOURCE.FAROL_NEBLINA = 'false' AND
    WH.DIM_RESOURCE.FREIO_ABS = STG.WEBMOTORS.FREIO_ABS AND
    WH.DIM_RESOURCE.GPS = STG.WEBMOTORS.GPS AND
    WH.DIM_RESOURCE.LIMPADOR_TRASEIRO = STG.WEBMOTORS.LIMPADOR_TRASEIRO AND
    WH.DIM_RESOURCE.PROTETOR_CACAMBA = STG.WEBMOTORS.PROTETOR_CACAMBA AND
    WH.DIM_RESOURCE.RADIO = STG.WEBMOTORS.RADIO AND
    WH.DIM_RESOURCE.RADIO_TOCAFITA = STG.WEBMOTORS.RADIO_TOCAFITA AND
    WH.DIM_RESOURCE.KIT_MULTIMIDIA = 'false' AND
    WH.DIM_RESOURCE.RETROVISOR_FOTOCROMICO = STG.WEBMOTORS.RETROVISOR_FOTOCROMICO AND
    WH.DIM_RESOURCE.RETROVISOR_ELETRICO = STG.WEBMOTORS.RETROVISOR_ELETRICO AND
    WH.DIM_RESOURCE.RODAS_LIGA_LEVE = STG.WEBMOTORS.RODAS_LIGA_LEVE AND
    WH.DIM_RESOURCE.SENSOR_DE_CHUVA = STG.WEBMOTORS.SENSOR_DE_CHUVA AND
    WH.DIM_RESOURCE.SENSOR_DE_ESTACIONAMENTO = STG.WEBMOTORS.SENSOR_DE_ESTACIONAMENTO AND
    WH.DIM_RESOURCE.TETO_SOLAR = STG.WEBMOTORS.TETO_SOLAR AND
    WH.DIM_RESOURCE.TRACAO_QUATRO_POR_QUATRO = STG.WEBMOTORS.TRACAO_QUATRO_POR_QUATRO AND
    WH.DIM_RESOURCE.TRAVAS_ELETRICAS = STG.WEBMOTORS.TRAVAS_ELETRICAS AND
    WH.DIM_RESOURCE.VIDROS_ELETRICOS = STG.WEBMOTORS.VIDROS_ELETRICOS AND
    WH.DIM_RESOURCE.VOLANTE_REG_ALTURA = STG.WEBMOTORS.VOLANTE_REG_ALTURA AND
    WH.DIM_RESOURCE.PILOTO_AUTOMATICO = 'false' AND
    WH.DIM_RESOURCE.ESCAPAMENTO_ESPORTIVO = 'false';