INSERT INTO WH.FACT_AD (
    AD_KEY,
    CAR_KEY,
    SELLER_KEY,
    LOCATION_KEY,
    RESOURCE_KEY,
    KILOMETRAGEM,
    PRECO,
    FIPE
) SELECT
    A.AD_KEY,
    A.CAR_KEY,
    A.SELLER_KEY,
    A.LOCATION_KEY,
    A.RESOURCE_KEY,
    A.KILOMETRAGEM,
    A.PRECO,
    A.PRECO_DESEJADO,
    A.FIPE
FROM STG.WEBMOTORS AS A;