INSERT INTO WH.DIM_SELLER (
    NOME_VENDEDOR,
    DOCUMENTO_VENDEDOR,
    EMAIL,
    CELULAR,
    TELEFONE,
    WHATSAPP,
    TIPO_VENDEDOR,
    VENDEDOR_PJ
) SELECT DISTINCT
    A.NOME_VENDEDOR,
    A.DOCUMENTO_VENDEDOR,
    A.EMAIL,
    A.CELULAR,
    A.TELEFONE,
    A.WHATSAPP,
    A.TIPO_VENDEDOR,
    A.VENDEDOR_PJ
FROM STG.AUTOLINE AS A;

UPDATE STG.AUTOLINE
SET STG.AUTOLINE.SELLER_KEY = WH.DIM_SELLER.SELLER_KEY
FROM STG.AUTOLINE
INNER JOIN WH.DIM_SELLER ON 
WH.DIM_AD.NOME_VENDEDOR = STG.AUTOLINE.NOME_VENDEDOR AND
WH.DIM_AD.DOCUMENTO_VENDEDOR = STG.AUTOLINE.DOCUMENTO_VENDEDOR AND
WH.DIM_AD.EMAIL = STG.AUTOLINE.EMAIL AND
WH.DIM_AD.CELULAR = STG.AUTOLINE.CELULAR AND
WH.DIM_AD.TELEFONE = STG.AUTOLINE.TELEFONE AND
WH.DIM_AD.WHATSAPP = STG.AUTOLINE.WHATSAPP AND
WH.DIM_AD.TIPO_VENDEDOR = STG.AUTOLINE.TIPO_VENDEDOR AND
WH.DIM_AD.VENDEDOR_PJ = STG.AUTOLINE.VENDEDOR_PJ AND;