INSERT INTO WH.DIM_AD (
    AD_ID,
    TITULO,
    ACEITA_TROCA,
    WEBSITE,
    LINK_AD
) SELECT DISTINCT
    A.AD_ID,
    A.INFORMACOES_ADICIONAIS,
    A.ACEITA_TROCA,
    A.WEBSITE,
    A.LINK_AD,
FROM STG.AUTOLINE AS A;

UPDATE STG.AUTOLINE
SET STG.AUTOLINE.AD_KEY = WH.DIM_AD.AD_KEY
FROM STG.AUTOLINE
INNER JOIN WH.DIM_AD ON 
WH.DIM_AD.AD_ID = STG.AUTOLINE.AD_ID AND
WH.DIM_AD.TITULO = STG.AUTOLINE.INFORMACOES_ADICIONAIS AND
WH.DIM_AD.TIPO_ANUNCIO = 'INDISPONIVEL' AND
WH.DIM_AD.ACEITA_TROCA = STG.AUTOLINE.ACEITA_TROCA AND
WH.DIM_AD.TROCA_COM_TROCO = 'false' AND
WH.DIM_AD.ENTREGA_CARRO = 'false' AND
WH.DIM_AD.COMENTARIO_DONO = 'INDISPONIVEL' AND
WH.DIM_AD.WEBSITE = STG.AUTOLINE.WEBSITE AND
WH.DIM_AD.LINK_AD = STG.AUTOLINE.LINK_AD AND;