INSERT INTO WH.DIM_LOCATION (
    CIDADE,
    ESTADO,
    UF,
    BAIRRO,
    ENDERECO,
    COMPLEMENTO_ENDERECO
) SELECT DISTINCT
    A.CIDADE,
    A.ESTADO,
    A.UF,
    A.BAIRRO,
    A.ENDERECO,
    A.COMPLEMENTO_ENDERECO
FROM STG.AUTOLINE AS A;

UPDATE STG.AUTOLINE
SET STG.AUTOLINE.LOCATION_KEY = WH.DIM_LOCATION.LOCATION_KEY
FROM STG.AUTOLINE
INNER JOIN WH.DIM_LOCATION ON 
WH.DIM_AD.CIDADE = STG.AUTOLINE.CIDADE AND
WH.DIM_AD.ESTADO = STG.AUTOLINE.ESTADO AND
WH.DIM_AD.UF = STG.AUTOLINE.UF AND
WH.DIM_AD.BAIRRO = STG.AUTOLINE.BAIRRO AND
WH.DIM_AD.ENDERECO = STG.AUTOLINE.ENDERECO AND
WH.DIM_AD.COMPLEMENTO_ENDERECO = STG.AUTOLINE.COMPLEMENTO_ENDERECO;