/* DIM_AD */

INSERT INTO WH.DIM_AD (
    AD_ID,
    TITULO,
    TIPO_ANUNCIO,
    ACEITA_TROCA,
    TROCA_COM_TROCO,
    ENTREGA_CARRO,
    COMENTARIO_DONO,
    WEBSITE
) SELECT DISTINCT
    A.AD_ID,
    A.TITULO,
    A.TIPO_ANUNCIO,
    A.ACEITA_TROCA,
    A.TROCA_COM_TROCO,
    A.ENTREGA_CARRO,
    A.COMENTARIO_DONO,
    A.WEBSITE
FROM STG.WEBMOTORS AS A;

DELETE  FROM
    WH.DIM_AD a
        USING WH.DIM_AD b
WHERE
    a.AD_KEY > b.AD_KEY AND
    a.AD_ID = b.AD_ID AND
    a.TITULO = b.TITULO AND
    a.TIPO_ANUNCIO = b.TIPO_ANUNCIO AND
    a.ACEITA_TROCA = b.ACEITA_TROCA AND
    a.TROCA_COM_TROCO = b.TROCA_COM_TROCO AND
    a.ENTREGA_CARRO = b.ENTREGA_CARRO AND
    a.COMENTARIO_DONO = b.COMENTARIO_DONO AND
    a.WEBSITE = b.WEBSITE AND
    a.LINK_AD = b.LINK_AD;

UPDATE STG.WEBMOTORS
SET AD_KEY = WH.DIM_AD.AD_KEY
FROM WH.DIM_AD
WHERE WH.DIM_AD.AD_ID = STG.WEBMOTORS.AD_ID AND
    WH.DIM_AD.TITULO = STG.WEBMOTORS.TITULO AND
    WH.DIM_AD.TIPO_ANUNCIO = STG.WEBMOTORS.TIPO_ANUNCIO AND
    WH.DIM_AD.ACEITA_TROCA = STG.WEBMOTORS.ACEITA_TROCA AND
    WH.DIM_AD.TROCA_COM_TROCO = STG.WEBMOTORS.TROCA_COM_TROCO AND
    WH.DIM_AD.ENTREGA_CARRO = STG.WEBMOTORS.ENTREGA_CARRO AND
    WH.DIM_AD.COMENTARIO_DONO = STG.WEBMOTORS.COMENTARIO_DONO  AND
    WH.DIM_AD.WEBSITE = STG.WEBMOTORS.WEBSITE;

/* DIM_CAR */

INSERT INTO WH.DIM_CAR (
    FABRICANTE,
    MODELO,
    VERSAO,
    ANO_FABRICACAO,
    ANO_MODELO,
    TRANSMISSAO,
    QNTD_PORTAS,
    CORPO_VEICULO,
    COR,
    COMBUSTIVEL
) SELECT DISTINCT
    A.FABRICANTE,
    A.MODELO,
    A.VERSAO,
    A.ANO_FABRICACAO,
    A.ANO_MODELO,
    A.TRANSMISSAO,
    A.QNTD_PORTAS,
    A.CORPO_VEICULO,
    A.COR,
    A.COMBUSTIVEL
FROM STG.WEBMOTORS AS A;

DELETE FROM
    WH.DIM_CAR a
        USING WH.DIM_CAR b
WHERE
    a.CAR_KEY > b.CAR_KEY AND
    a.FABRICANTE = b.FABRICANTE AND
    a.TIPO_VEICULO = b.TIPO_VEICULO AND
    a.MODELO = b.MODELO AND
    a.VERSAO = b.VERSAO AND
    a.ANO_FABRICACAO = b.ANO_FABRICACAO AND
    a.ANO_MODELO = b.ANO_MODELO AND
    a.TRANSMISSAO = b.TRANSMISSAO AND
    a.QNTD_PORTAS = b.QNTD_PORTAS AND
    a.CORPO_VEICULO = b.CORPO_VEICULO AND
    a.COR = b.COR AND
    a.COR_SECUNDARIA = b.COR_SECUNDARIA AND
    a.COMBUSTIVEL = b.COMBUSTIVEL AND
    a.MOTOR = b.MOTOR AND
    a.PLACA = b.PLACA;

UPDATE STG.WEBMOTORS
SET CAR_KEY = WH.DIM_CAR.CAR_KEY
FROM WH.DIM_CAR
WHERE WH.DIM_CAR.FABRICANTE = STG.WEBMOTORS.FABRICANTE AND
    WH.DIM_CAR.TIPO_VEICULO = 'INDISPONIVEL' AND
    WH.DIM_CAR.MODELO = STG.WEBMOTORS.MODELO AND
    WH.DIM_CAR.VERSAO = STG.WEBMOTORS.VERSAO AND
    WH.DIM_CAR.ANO_FABRICACAO = STG.WEBMOTORS.ANO_FABRICACAO AND
    WH.DIM_CAR.ANO_MODELO = STG.WEBMOTORS.ANO_MODELO AND
    WH.DIM_CAR.TRANSMISSAO = STG.WEBMOTORS.TRANSMISSAO AND
    WH.DIM_CAR.QNTD_PORTAS = STG.WEBMOTORS.QNTD_PORTAS AND
    WH.DIM_CAR.CORPO_VEICULO = STG.WEBMOTORS.CORPO_VEICULO AND
    WH.DIM_CAR.COR = STG.WEBMOTORS.COR AND
    WH.DIM_CAR.COR_SECUNDARIA = 'INDISPONIVEL' AND
    WH.DIM_CAR.COMBUSTIVEL = STG.WEBMOTORS.COMBUSTIVEL AND
    WH.DIM_CAR.MOTOR = 'INDISPONIVEL' AND
    WH.DIM_CAR.PLACA = 'INDISPONIVEL';

/* DIM_LOCATION */

INSERT INTO WH.DIM_LOCATION (
    CIDADE,
    ESTADO,
    UF
) SELECT DISTINCT
    A.CIDADE_VENDEDOR,
    A.ESTADO_VENDEDOR,
    A.UF_VENDEDOR
FROM STG.WEBMOTORS AS A;

DELETE FROM
    WH.DIM_LOCATION a
        USING WH.DIM_LOCATION b
WHERE
    a.LOCATION_KEY > b.LOCATION_KEY AND
    a.CIDADE = b.CIDADE AND
    a.ESTADO = b.ESTADO AND
    a.UF = b.UF AND
    a.BAIRRO = b.BAIRRO AND
    a.ENDERECO = b.ENDERECO AND
    a.COMPLEMENTO_ENDERECO = b.COMPLEMENTO_ENDERECO;

UPDATE STG.WEBMOTORS
SET LOCATION_KEY = WH.DIM_LOCATION.LOCATION_KEY
FROM WH.DIM_LOCATION
WHERE WH.DIM_LOCATION.CIDADE = STG.WEBMOTORS.CIDADE_VENDEDOR AND
    WH.DIM_LOCATION.ESTADO = STG.WEBMOTORS.ESTADO_VENDEDOR AND
    WH.DIM_LOCATION.UF = STG.WEBMOTORS.UF_VENDEDOR AND
    WH.DIM_LOCATION.BAIRRO = 'INDISPONIVEL' AND
    WH.DIM_LOCATION.ENDERECO = 'INDISPONIVEL' AND
    WH.DIM_LOCATION.COMPLEMENTO_ENDERECO = 'INDISPONIVEL';

/* DIM_RESOURCE */

INSERT INTO WH.DIM_RESOURCE (
    ALIENADO,
    REVISOES_PELA_AGENDA_CARRO,
    REVISOES_PELA_CONCESSIONARIA,
    UNICO_DONO,
    BLINDADO,
    LICENCIADO,
    IPVA_PAGO,
    GARANTIA_DE_FABRICA,
    AIRBAG,
    ALARME,
    AR_CONDICIONADO,
    AR_QUENTE,
    BANCO_REGULA_ALTURA,
    BANCO_COM_AQUECIMENTO,
    BANCO_DE_COURO,
    CAPOTA_MARITIMA,
    MP3_CD_PLAYER,
    CD_PLAYER,
    DISQUETEIRA,
    DVD_PLAYER,
    COMPUTAR_DE_BORDO,
    CONTROLE_AUTOMATICO_VEL,
    CONTROLE_TRACAO,
    DESEMBACADOR_TRASEIRO,
    DIR_HIDRAULICA,
    ENCOSTO_CABECA_TRASEIRO,
    FAROL_DE_XENONIO,
    FREIO_ABS,
    GPS,
    LIMPADOR_TRASEIRO,
    PROTETOR_CACAMBA,
    RADIO,
    RADIO_TOCAFITA,
    RETROVISOR_FOTOCROMICO,
    RETROVISOR_ELETRICO,
    RODAS_LIGA_LEVE,
    SENSOR_DE_CHUVA,
    SENSOR_DE_ESTACIONAMENTO,
    TETO_SOLAR,
    TRACAO_QUATRO_POR_QUATRO,
    TRAVAS_ELETRICAS,
    VIDROS_ELETRICOS,
    VOLANTE_REG_ALTURA
) SELECT DISTINCT
    A.ALIENADO,
    A.REVISOES_PELA_AGENDA_CARRO,
    A.REVISOES_PELA_CONCESSIONARIA,
    A.UNICO_DONO,
    A.BLINDADO,
    A.LICENCIADO,
    A.IPVA_PAGO,
    A.GARANTIA_DE_FABRICA,
    A.AIRBAG,
    A.ALARME,
    A.AR_CONDICIONADO,
    A.AR_QUENTE,
    A.BANCO_REGULA_ALTURA,
    A.BANCO_COM_AQUECIMENTO,
    A.BANCO_DE_COURO,
    A.CAPOTA_MARITIMA,
    A.MP3_CD_PLAYER,
    A.CD_PLAYER,
    A.DISQUETEIRA,
    A.DVD_PLAYER,
    A.COMPUTAR_DE_BORDO,
    A.CONTROLE_AUTOMATICO_VEL,
    A.CONTROLE_TRACAO,
    A.DESEMBACADOR_TRASEIRO,
    A.DIR_HIDRAULICA,
    A.ENCOSTO_CABECA_TRASEIRO,
    A.FAROL_DE_XENONIO,
    A.FREIO_ABS,
    A.GPS,
    A.LIMPADOR_TRASEIRO,
    A.PROTETOR_CACAMBA,
    A.RADIO,
    A.RADIO_TOCAFITA,
    A.RETROVISOR_FOTOCROMICO,
    A.RETROVISOR_ELETRICO,
    A.RODAS_LIGA_LEVE,
    A.SENSOR_DE_CHUVA,
    A.SENSOR_DE_ESTACIONAMENTO,
    A.TETO_SOLAR,
    A.TRACAO_QUATRO_POR_QUATRO,
    A.TRAVAS_ELETRICAS,
    A.VIDROS_ELETRICOS,
    A.VOLANTE_REG_ALTURA
FROM STG.WEBMOTORS AS A;

DELETE FROM
    WH.DIM_RESOURCE a
        USING WH.DIM_RESOURCE b
WHERE
    a.RESOURCE_KEY > b.RESOURCE_KEY AND
    a.FINANCIAVEL = b.FINANCIAVEL AND
    a.FINANCIADO = b.FINANCIADO AND
    a.IMPOSTOS_PAGOS = b.IMPOSTOS_PAGOS AND
    a.REGISTRAMENTO_PAGO = b.REGISTRAMENTO_PAGO AND
    a.QUITADO = b.QUITADO AND
    a.ALIENADO = b.ALIENADO AND
    a.REVISOES_PELA_AGENDA_CARRO = b.REVISOES_PELA_AGENDA_CARRO AND
    a.REVISOES_PELA_CONCESSIONARIA = b.REVISOES_PELA_CONCESSIONARIA AND
    a.UNICO_DONO = b.UNICO_DONO AND
    a.COLECIONADOR = b.COLECIONADOR AND
    a.ADAPTADO_DEFICIENCIA = b.ADAPTADO_DEFICIENCIA AND
    a.BLINDADO = b.BLINDADO AND
    a.LICENCIADO = b.LICENCIADO AND
    a.IPVA_PAGO = b.IPVA_PAGO AND
    a.GARANTIA_DE_FABRICA = b.GARANTIA_DE_FABRICA AND
    a.AIRBAG = b.AIRBAG AND
    a.AIRBAG_DUPLO = b.AIRBAG_DUPLO AND
    a.ALARME = b.ALARME AND
    a.AR_CONDICIONADO = b.AR_CONDICIONADO AND
    a.AR_QUENTE = b.AR_QUENTE AND
    a.BANCO_REGULA_ALTURA = b.BANCO_REGULA_ALTURA AND
    a.BANCO_COM_AQUECIMENTO = b.BANCO_COM_AQUECIMENTO AND
    a.BANCO_DE_COURO = b.BANCO_DE_COURO AND
    a.CAPOTA_MARITIMA = b.CAPOTA_MARITIMA AND
    a.MP3_CD_PLAYER = b.MP3_CD_PLAYER AND
    a.CD_PLAYER = b.CD_PLAYER AND
    a.DISQUETEIRA = b.DISQUETEIRA AND
    a.DVD_PLAYER = b.DVD_PLAYER AND
    a.COMPUTAR_DE_BORDO = b.COMPUTAR_DE_BORDO AND
    a.CONTROLE_AUTOMATICO_VEL = b.CONTROLE_AUTOMATICO_VEL AND
    a.CONTROLE_TRACAO = b.CONTROLE_TRACAO AND
    a.DESEMBACADOR_TRASEIRO = b.DESEMBACADOR_TRASEIRO AND
    a.DIR_HIDRAULICA = b.DIR_HIDRAULICA AND
    a.DIR_ELETRICA = b.DIR_ELETRICA AND
    a.ENCOSTO_CABECA_TRASEIRO = b.ENCOSTO_CABECA_TRASEIRO AND
    a.FAROL_DE_XENONIO = b.FAROL_DE_XENONIO AND
    a.FAROL_DE_MILHA = b.FAROL_DE_MILHA AND
    a.FAROL_NEBLINA = b.FAROL_NEBLINA AND
    a.FREIO_ABS = b.FREIO_ABS AND
    a.GPS = b.GPS AND
    a.LIMPADOR_TRASEIRO = b.LIMPADOR_TRASEIRO AND
    a.PROTETOR_CACAMBA = b.PROTETOR_CACAMBA AND
    a.RADIO = b.RADIO AND
    a.RADIO_TOCAFITA = b.RADIO_TOCAFITA AND
    a.KIT_MULTIMIDIA = b.KIT_MULTIMIDIA AND
    a.RETROVISOR_FOTOCROMICO = b.RETROVISOR_FOTOCROMICO AND
    a.RETROVISOR_ELETRICO = b.RETROVISOR_ELETRICO AND
    a.RODAS_LIGA_LEVE = b.RODAS_LIGA_LEVE AND
    a.SENSOR_DE_CHUVA = b.SENSOR_DE_CHUVA AND
    a.SENSOR_DE_ESTACIONAMENTO = b.SENSOR_DE_ESTACIONAMENTO AND
    a.TETO_SOLAR = b.TETO_SOLAR AND
    a.TRACAO_QUATRO_POR_QUATRO = b.TRACAO_QUATRO_POR_QUATRO AND
    a.TRAVAS_ELETRICAS = b.TRAVAS_ELETRICAS AND
    a.VIDROS_ELETRICOS = b.VIDROS_ELETRICOS AND
    a.VOLANTE_REG_ALTURA = b.VOLANTE_REG_ALTURA AND
    a.PILOTO_AUTOMATICO = b.PILOTO_AUTOMATICO AND
    a.ESCAPAMENTO_ESPORTIVO = b.ESCAPAMENTO_ESPORTIVO;

UPDATE STG.WEBMOTORS
SET RESOURCE_KEY = WH.DIM_RESOURCE.RESOURCE_KEY
FROM WH.DIM_RESOURCE
WHERE WH.DIM_RESOURCE.FINANCIAVEL = 'false' AND
    WH.DIM_RESOURCE.FINANCIADO = 'false' AND
    WH.DIM_RESOURCE.IMPOSTOS_PAGOS = 'false' AND
    WH.DIM_RESOURCE.REGISTRAMENTO_PAGO = 'false' AND
    WH.DIM_RESOURCE.QUITADO = 'false' AND
    WH.DIM_RESOURCE.ALIENADO = STG.WEBMOTORS.ALIENADO AND
    WH.DIM_RESOURCE.REVISOES_PELA_AGENDA_CARRO = STG.WEBMOTORS.REVISOES_PELA_AGENDA_CARRO AND
    WH.DIM_RESOURCE.REVISOES_PELA_CONCESSIONARIA = STG.WEBMOTORS.REVISOES_PELA_CONCESSIONARIA AND
    WH.DIM_RESOURCE.UNICO_DONO = STG.WEBMOTORS.UNICO_DONO AND
    WH.DIM_RESOURCE.COLECIONADOR = 'false'AND
    WH.DIM_RESOURCE.ADAPTADO_DEFICIENCIA = 'false' AND
    WH.DIM_RESOURCE.BLINDADO = STG.WEBMOTORS.BLINDADO AND
    WH.DIM_RESOURCE.LICENCIADO = STG.WEBMOTORS.LICENCIADO AND
    WH.DIM_RESOURCE.IPVA_PAGO = STG.WEBMOTORS.IPVA_PAGO  AND
    WH.DIM_RESOURCE.GARANTIA_DE_FABRICA = STG.WEBMOTORS.GARANTIA_DE_FABRICA AND
    WH.DIM_RESOURCE.AIRBAG = STG.WEBMOTORS.AIRBAG AND
    WH.DIM_RESOURCE.AIRBAG_DUPLO = 'false' AND
    WH.DIM_RESOURCE.ALARME = STG.WEBMOTORS.ALARME AND
    WH.DIM_RESOURCE.AR_CONDICIONADO = STG.WEBMOTORS.AR_CONDICIONADO AND
    WH.DIM_RESOURCE.AR_QUENTE = STG.WEBMOTORS.AR_QUENTE AND
    WH.DIM_RESOURCE.BANCO_REGULA_ALTURA = STG.WEBMOTORS.BANCO_REGULA_ALTURA AND
    WH.DIM_RESOURCE.BANCO_COM_AQUECIMENTO = STG.WEBMOTORS.BANCO_COM_AQUECIMENTO AND
    WH.DIM_RESOURCE.BANCO_DE_COURO = STG.WEBMOTORS.BANCO_DE_COURO AND
    WH.DIM_RESOURCE.CAPOTA_MARITIMA = STG.WEBMOTORS.CAPOTA_MARITIMA AND
    WH.DIM_RESOURCE.MP3_CD_PLAYER = STG.WEBMOTORS.MP3_CD_PLAYER AND
    WH.DIM_RESOURCE.CD_PLAYER = STG.WEBMOTORS.CD_PLAYER AND
    WH.DIM_RESOURCE.DISQUETEIRA = STG.WEBMOTORS.DISQUETEIRA AND
    WH.DIM_RESOURCE.DVD_PLAYER = STG.WEBMOTORS.DVD_PLAYER AND
    WH.DIM_RESOURCE.COMPUTAR_DE_BORDO = STG.WEBMOTORS.COMPUTAR_DE_BORDO AND
    WH.DIM_RESOURCE.CONTROLE_AUTOMATICO_VEL = STG.WEBMOTORS.CONTROLE_AUTOMATICO_VEL AND
    WH.DIM_RESOURCE.CONTROLE_TRACAO = STG.WEBMOTORS.CONTROLE_TRACAO AND
    WH.DIM_RESOURCE.DESEMBACADOR_TRASEIRO = STG.WEBMOTORS.DESEMBACADOR_TRASEIRO AND
    WH.DIM_RESOURCE.DIR_HIDRAULICA = STG.WEBMOTORS.DIR_HIDRAULICA AND
    WH.DIM_RESOURCE.DIR_ELETRICA = 'false'AND
    WH.DIM_RESOURCE.ENCOSTO_CABECA_TRASEIRO = STG.WEBMOTORS.ENCOSTO_CABECA_TRASEIRO AND
    WH.DIM_RESOURCE.FAROL_DE_XENONIO = STG.WEBMOTORS.FAROL_DE_XENONIO AND
    WH.DIM_RESOURCE.FAROL_DE_MILHA = 'false' AND
    WH.DIM_RESOURCE.FAROL_NEBLINA = 'false' AND
    WH.DIM_RESOURCE.FREIO_ABS = STG.WEBMOTORS.FREIO_ABS AND
    WH.DIM_RESOURCE.GPS = STG.WEBMOTORS.GPS AND
    WH.DIM_RESOURCE.LIMPADOR_TRASEIRO = STG.WEBMOTORS.LIMPADOR_TRASEIRO AND
    WH.DIM_RESOURCE.PROTETOR_CACAMBA = STG.WEBMOTORS.PROTETOR_CACAMBA AND
    WH.DIM_RESOURCE.RADIO = STG.WEBMOTORS.RADIO AND
    WH.DIM_RESOURCE.RADIO_TOCAFITA = STG.WEBMOTORS.RADIO_TOCAFITA AND
    WH.DIM_RESOURCE.KIT_MULTIMIDIA = 'false' AND
    WH.DIM_RESOURCE.RETROVISOR_FOTOCROMICO = STG.WEBMOTORS.RETROVISOR_FOTOCROMICO AND
    WH.DIM_RESOURCE.RETROVISOR_ELETRICO = STG.WEBMOTORS.RETROVISOR_ELETRICO AND
    WH.DIM_RESOURCE.RODAS_LIGA_LEVE = STG.WEBMOTORS.RODAS_LIGA_LEVE AND
    WH.DIM_RESOURCE.SENSOR_DE_CHUVA = STG.WEBMOTORS.SENSOR_DE_CHUVA AND
    WH.DIM_RESOURCE.SENSOR_DE_ESTACIONAMENTO = STG.WEBMOTORS.SENSOR_DE_ESTACIONAMENTO AND
    WH.DIM_RESOURCE.TETO_SOLAR = STG.WEBMOTORS.TETO_SOLAR AND
    WH.DIM_RESOURCE.TRACAO_QUATRO_POR_QUATRO = STG.WEBMOTORS.TRACAO_QUATRO_POR_QUATRO AND
    WH.DIM_RESOURCE.TRAVAS_ELETRICAS = STG.WEBMOTORS.TRAVAS_ELETRICAS AND
    WH.DIM_RESOURCE.VIDROS_ELETRICOS = STG.WEBMOTORS.VIDROS_ELETRICOS AND
    WH.DIM_RESOURCE.VOLANTE_REG_ALTURA = STG.WEBMOTORS.VOLANTE_REG_ALTURA AND
    WH.DIM_RESOURCE.PILOTO_AUTOMATICO = 'false' AND
    WH.DIM_RESOURCE.ESCAPAMENTO_ESPORTIVO = 'false';

/* DIM_SELLER */

INSERT INTO WH.DIM_SELLER (
    TIPO_VENDEDOR
) SELECT DISTINCT
    A.TIPO_VENDEDOR
FROM STG.WEBMOTORS AS A;

DELETE FROM
    WH.DIM_SELLER a
        USING WH.DIM_SELLER b
WHERE
    a.SELLER_KEY > b.SELLER_KEY AND
    a.NOME_VENDEDOR = b.NOME_VENDEDOR AND
    a.DOCUMENTO_VENDEDOR = b.DOCUMENTO_VENDEDOR AND
    a.EMAIL = b.EMAIL AND
    a.CELULAR = b.CELULAR AND
    a.TELEFONE = b.TELEFONE AND
    a.WHATSAPP = b.WHATSAPP AND
    a.TIPO_VENDEDOR = b.TIPO_VENDEDOR AND
    a.VENDEDOR_PJ = b.VENDEDOR_PJ;

UPDATE STG.WEBMOTORS
SET SELLER_KEY = WH.DIM_SELLER.SELLER_KEY
FROM WH.DIM_SELLER
WHERE WH.DIM_SELLER.NOME_VENDEDOR = 'INDISPONIVEL'  AND
    WH.DIM_SELLER.DOCUMENTO_VENDEDOR = 'INDISPONIVEL'  AND
    WH.DIM_SELLER.EMAIL = 'INDISPONIVEL'  AND
    WH.DIM_SELLER.CELULAR = 'INDISPONIVEL'  AND
    WH.DIM_SELLER.TELEFONE = 'INDISPONIVEL'  AND
    WH.DIM_SELLER.WHATSAPP = 'INDISPONIVEL'  AND
    WH.DIM_SELLER.TIPO_VENDEDOR = STG.WEBMOTORS.TIPO_VENDEDOR AND
    WH.DIM_SELLER.VENDEDOR_PJ = 'false';

/* FACT_AD */

INSERT INTO WH.FACT_AD (
    AD_KEY,
    CAR_KEY,
    SELLER_KEY,
    LOCATION_KEY,
    RESOURCE_KEY,
    KILOMETRAGEM,
    PRECO,
    PRECO_DESEJADO,
    FIPE,
    DATA_CARGA
) SELECT DISTINCT
    A.AD_KEY,
    A.CAR_KEY,
    A.SELLER_KEY,
    A.LOCATION_KEY,
    A.RESOURCE_KEY,
    A.KILOMETRAGEM,
    A.PRECO,
    A.PRECO_DESEJADO,
    A.PORCENTAGEM_FIPE,
    DATA_CARGA
FROM STG.WEBMOTORS AS A;

DELETE FROM
    WH.FACT_AD a
        USING WH.FACT_AD b
WHERE
    a.ROW_ID > b.ROW_ID AND
    a.AD_KEY = b.AD_KEY AND
    a.CAR_KEY = b.CAR_KEY AND
    a.SELLER_KEY = b.SELLER_KEY AND
    a.LOCATION_KEY = b.LOCATION_KEY AND
    a.RESOURCE_KEY = b.RESOURCE_KEY AND
    a.KILOMETRAGEM = b.KILOMETRAGEM AND
    a.PRECO = b.PRECO AND
    a.PRECO_DESEJADO = b.PRECO_DESEJADO AND
    a.FIPE = b.FIPE;